import json
from pathlib import Path
sources=json.load(open('books/RyanLPeterman/editorial/worker3-extra.json'))['sources']
def qa(q,a,x,y,speaker='Ryan Peterman',followups=[]):return {'type':'qa','question':q,'answer':a,'speaker':speaker,'evidence':[{'start':x,'end':y}],'followups':followups}
def fu(q,a,x,y,speaker):return {'question':q,'answer':a,'speaker':speaker,'evidence':[{'start':x,'end':y}]}
def save(index,title,deck,blocks,theme,omissions=[],kind='interview',notes=''):
 s=sources[index]
 out={'section':{'id':s['id'],'source_id':s['id'],'title':title,'kind':kind,'deck':deck,'blocks':blocks,'related':[],'omissions':omissions},'coverage':{'source_id':s['id'],'sha256':s['sha256'],'reviewed_chunks':[c['number'] for c in s['chunks']],'status':'included','reason':'Read every assigned compact-reading chunk in full; retained all substantive discussion and ordered question rounds.'},'editorial':{'theme':theme,'question_rounds':sum(x['type']=='qa' for x in blocks),'followup_count':sum(len(x.get('followups',[])) for x in blocks),'notes':notes}}
 Path('books/RyanLPeterman/sections/'+s['id']+'.json').write_text(json.dumps(out,indent=2))
b=[qa('Why create a podcast about senior engineers’ careers?',[
'Ryan wanted to become a better speaker, a skill he believes affects careers, relationships, and how others perceive someone. Toastmasters supplied useful practice, but he found that recordings often went unreviewed amid other priorities. Publishing created a stronger commitment: because people would listen, he examined every word during editing. The content became both practice and a feedback loop.',
'He chose an initially modest goal of one episode per month because he already had substantial responsibilities. The process turned out to be enjoyable in its own right: he could have conversations he wanted to have with engineers he admired. Internal Facebook career narratives had earlier absorbed him with their accounts of impressive work and growth. The podcast sought to bring those otherwise little-known stories to a wider industry audience.'
],62.8,329.04),qa('What surprised you behind the scenes of successful episodes?',[
'Ryan remembers being unusually absorbed while recording with Philip Su, whose writing he had admired inside Meta. Strong engagement during the conversation and rapid audience growth afterward suggested that other engineers valued these career stories too. He felt similar energy with Ethan Evans and especially admired the guest’s ability to speak clearly.',
'Trailers created a separate challenge. Established shows can rely on reputation, but a new show may need to explain quickly why an unfamiliar guest is worth hearing. An especially aggressive trailer thrilled him at first, then audience feedback pushed him to balance attention-grabbing excerpts with taste and ease of listening. He considers shorter or absent trailers for recurring audio-podcast listeners while keeping a carefully edited introduction for discovery on YouTube. These are his plans at the time, rather than a promise about the current distribution format.'
],330.72,604.72),qa('Which future guests are you trying to find?',[
'His ideal guests are highly accomplished engineers known within their company or organization but not necessarily famous publicly. They may have substantial technical and career stories without being active on social media. Standard searches do not reliably reveal that group.',
'His own big-tech network supplied early guests. Audience recommendations then became a way to find admired senior ICs at other companies. He describes viewers’ suggestions leading to planned conversations at Apple, Google, and Microsoft. The sourcing challenge explains why community participation matters to the show’s editorial direction.'
],607.04,722.24),qa('What was harder about podcasting than ordinary conversation?',[
'Natural verbal acknowledgments—short agreements and listening noises—can obscure a guest’s answer in an audio recording. Ryan had to learn to express engagement with nods while holding back interruptions. Producing something pleasant to hear calls for a different listening habit than an unrecorded conversation.'
],723.76,788.56),qa('How do you balance a full-time engineering job with publishing?',[
'He finds it difficult and rejects an effortless side-project picture. For roughly two years he often stayed up until about four in the morning on Thursdays to finish a newsletter. A fellow newsletter writer cautioned him about burning the candle at both ends, and experience convinced him the warning was justified.',
'Content work pushes out other parts of life when meeting the day job’s expectations already takes substantial effort. He believes additional family or time commitments would have made the arrangement much harder. The account is an honest cost description, not a recommended sustainable schedule.'
],790.56,900.32)]
save(0,'A learning project becomes a community of engineering stories','Ryan Peterman explains how the podcast grew from deliberate speaking practice into a way to surface engineers whose work is better known inside companies than outside them.',b,'community',['Introductory explanation of the rescheduled recording and unused studio booking at 00:00–00:58 is summarized only as production context.','Closing engagement requests and repeated guest-sourcing call after the work-balance discussion are omitted.'],notes='The five actual interview questions are retained. The opening prompt is a trailer/context lead rather than an additional substantive exchange. The uncertain newsletter-writer name is omitted.')
b=[qa('How would you find the minimum insertions, deletions, or replacements needed to convert one string into another?',[
'Neetcode recognizes edit distance and begins with recursion rather than claiming to remember every detail. Matching characters let the comparison advance without an edit. A mismatch creates three possible actions—insert, delete, or replace—and exploring those choices supplies a recursive starting point that can be memoized.',
'He then sketches a two-dimensional dynamic-programming grid, with dimensions corresponding to the strings and expected O(n × m) time. The exchange does not finish the transition formula, boundary cases, or implementation. He briefly says “maximum” while describing possible recursive results despite the prompt asking for a minimum; the correct-looking direction should not be mistaken for a fully checked recurrence.'
],0.08,166.48,speaker='Neetcode',followups=[fu('What does one cell of the grid represent?',[
'He works toward the edit distance between prefixes of the two words, with later cells derived from previously solved subproblems. The host clarifies that interpretation, and Neetcode agrees. He admits that mapping each edit action to a neighboring cell is the part requiring more careful thought and would usually start writing code to make it precise.',
'He says deriving the DP from the recursive solution is easier than jumping straight to the grid. A concrete example can show why different actions are needed, but this verbal sketch stops before completing all cases. The host’s diagnosis is that the candidate is going in the right direction and still needs time for case analysis.'
],169.76,347.84,'Neetcode')]),qa('How would you find the median of two sorted arrays?',[
'He knows binary search is associated with the problem but does not remember the elimination rule. He constructs an example with overlapping values and duplicates and talks about time management: elaborate diagrams might help reasoning but consume limited interview time.',
'A brief exchange corrects the task from finding a target to finding the median. With nine total elements in his example, he knows the fifth ordered element is the goal. He tests whether part of one array can safely be eliminated and recognizes that comparisons must involve both arrays. He then considers comparing the arrays’ medians and flags odd/even and off-by-one complications.',
'The segment ends with a partial reconstruction, not a complete algorithm or correctness argument. He says it has been about five years since making his solution video and uses the struggle to show how first-principles reasoning can get him closer without instant recall. The host moves on rather than supplying a finished solution.'
],312.16,629.28,speaker='Neetcode'),qa('How would you count placements of n queens on an n-by-n board with no mutual attacks?',[
'He proposes backtracking over placements and skipping moves already attacked by another queen. Sets or similar hash structures can record occupied rows and columns. The challenge is identifying diagonal membership without scanning the board.',
'He derives one diagonal key by noting that increasing a row while decreasing a column keeps their sum constant. After some hesitation he derives the other direction from the row-column difference. With row, column, and both diagonal keys, a tentative placement can be checked through quick membership lookups before recursing.',
'The host accepts the overall direction. Neetcode does not provide code, a complete enumeration scheme, or a verified time complexity; he notes that the search tree is large and probably exponential, even though each membership lookup is constant time. His belief that the approach is optimal is not proved in the exchange.'
],628.0,943.44,speaker='Neetcode',followups=[fu('Are the diagonal keys just a way to test quickly whether a diagonal is occupied?',[
'Yes. Neetcode confirms that the goal is a key-based membership lookup, then completes the distinction between constant sums on one diagonal direction and constant differences on the other. The clarification helps him finish the reasoning he had been reconstructing.'
],833.04,894.32,'Neetcode')])]
save(1,'Reasoning through hard interview problems without perfect recall','A live whiteboard exercise preserves the useful partial reasoning, clarifications, and remaining gaps in three familiar algorithm problems.',b,'hiring',kind='coaching',notes='All three substantive problem prompts are distinct QA blocks. The transcript contains verbal sketches and partial derivations, not completed code. The unresolved median algorithm, edit-distance transition ambiguity, and unverified N-Queens complexity are retained explicitly.')
b=[qa('Have reports escalated problems with their managers to you, and why might a skip-level leader resist acting?',[
'Ethan Evans says such escalations were common. He describes an uncomfortable incentive: accepting one report’s account can create three problems for the skip-level leader—deciding what to do about the manager, replacing and training someone if necessary, and covering the work in between. Dismissing the report as oversensitive instead makes the problem easier to delegate back to the manager. Evans presents this as a possible subconscious bias, not a defense of ignoring a valid concern.',
'He recounts discovering a leader’s poor treatment of women only after several reports accumulated and he spoke with affected colleagues. A lone earlier report might not have moved him, a failure he describes candidly. Multiple independently supported accounts changed his understanding. He therefore recommends corroboration when colleagues are willing to provide it; the speaker’s “mutiny” metaphor concerns workplace escalation and should not obscure the seriousness of the example.'
],0.0,183.72,speaker='Ethan Evans',followups=[fu('Should a high-performing IC compare observations with colleagues before escalating?',[
'If possible, yes. It first checks whether the problem is a broader pattern or a working-style mismatch. A colleague who works well with the manager may offer a useful adjustment; colleagues seeing the same problem may corroborate it. Shared dissatisfaction is not enough unless they are also willing to speak.',
'Evans proposes telling the skip-level leader that named colleagues are willing to share similar examples and asking the leader to speak with them. He thinks many leaders will do that, while explicitly refusing to guarantee it. The host flags the difference between casual complaints and formal escalation, including the possibility of retaliation or being wrong.'
],184.96,321.32,'Ethan Evans')]),qa('Could you seek a move for business reasons instead of organizing an escalation?',[
'Evans separates two approaches. If there is a genuinely plausible case that another role would make the engineer equally or more valuable to the organization, lead with that case and do not introduce the manager complaint. If the real need is incompatible working relationships, explain that blame-free and think several moves ahead about the choices the leader actually has.',
'He describes his own move at Amazon. His leader wanted to keep him in the current role, but Evans had another available role outside that leader’s organization as well as a preferred role inside it. Explaining that remaining where he was had ceased to be an available choice changed the decision from “keep him here or move him internally” to “keep him in the organization or lose him.” After weeks of resistance, the internal move happened quickly. The story depends on having real alternatives, not on inventing an outside offer.'
],275.6,486.48,speaker='Ethan Evans'),qa('How did you communicate those alternatives without sounding threatening?',[
'He framed the situation in terms the leader would recognize. Both were vice presidents, and the alternative offer came from a senior vice president. Evans explained that he needed to answer and that once he gave his word, he would have to honor it—as the leader himself would. That let the leader understand the constraint without a blunt demand.',
'Evans recommends preparing the key phrase before a predictable conversation rather than improvising under pressure. The facts and commitment should remain true; careful framing changes how the other person receives them. Delivery matters too. The same statement about needing to consider one’s career can sound hostile or calm and understandable depending on tone and body language.',
'He acknowledges that some engineers dislike workplace politics. His argument is that leaders still have emotions, stress, and defensiveness, so understanding the human interaction helps a person communicate an honest need more effectively. He does not claim he has fully figured out how to teach the skill.'
],487.32,754.28,speaker='Ethan Evans',followups=[fu('Were there three different roles involved?',[
'Yes: the current role, the role he wanted inside the same organization, and another available role elsewhere. The host characterizes the alternative as leverage. Evans agrees with the underlying structure while emphasizing that he did not explicitly issue a threat; he stated the true consequence of accepting another offer and giving his word.'
],575.24,624.24,'Ethan Evans')])]
save(2,'Escalation, corroboration, and credible alternatives','Ethan Evans explains why leaders can resist evidence of a weak manager and how careful, truthful framing can make a difficult career conversation easier to hear.',b,'leadership',kind='companion',notes='All substantive prompts and clarifications are retained in source order. The account of bias against a lone complaint is attributed to Evans and not endorsed as fair management. The transfer story retains its real alternatives and truthfulness qualifications.')
b=[qa('What distinguishes the work at E7, E8, and E9?',[
'Philip Su begins with scope of influence: how large, valuable, or long-running an effort can someone reliably bring to completion? He offers approximate historical expectations, such as influencing roughly ten to fifteen people at senior/staff-adjacent levels and perhaps fifty at E7. He explicitly warns that his leveling information may be stale. These are illustrations from his experience, not a promotion standard for any company today.',
'Higher levels also differ qualitatively. An unusually deep specialist may solve problems that several less-senior engineers cannot substitute for. A broad generalist may integrate many kinds of work for a small or new team more effectively than separate hires. Headcount alone misses that distinction.',
'He recalls E9 being created after his initial E8 promotion and early decisions involving only a few very different candidates. Such a small and varied group makes a universal checklist implausible. At the top, informed judgment from peers and more-senior leaders matters: do they recognize work of that level, and why? He compares it to the qualitative recognition involved in academic seniority. The point is not that all evaluation is arbitrary, but that a list of tasks cannot fully represent exceptional and varied contributions.'
],0.16,337.68,speaker='Philip Su'),qa('What if a strong E7 has no E8 or E9 nearby to learn from or assess them?',[
'Su recognizes the problem both in small companies and in weaker teams inside huge organizations. Being the strongest local person can distort self-calibration or remove opportunities to observe better judgment. He recommends an environment where there is room to grow alongside strong colleagues, rather than treating being locally best as the only goal.',
'At very high levels, merely copying another senior person may not work because their archetype and strengths can differ from yours. He favors access to a coach who participates in the relevant promotion decisions and can give a qualitative assessment. That person can explain where the work remains short of the bar and help discuss what stronger work would look like. The desired input is specific feedback, not an assumption that proximity to a prestigious title automatically produces growth.'
],338.64,483.36,speaker='Philip Su'),qa('What scope of work contributed to your own E9 promotion?',[
'Su helped start Meta’s London engineering presence with twelve people and, over roughly four or five years, grow it to around four or five hundred. He describes managing the strategic and organizational transitions as the site expanded. A team of twelve could be run well by a capable engineering manager; several orders of magnitude of growth made problems more varied and answers less clear-cut.',
'One example was planning London internships and headcount based on anticipated visa constraints affecting future full-time arrivals in Menlo Park. He used data to recommend decisions roughly eighteen months before their consequences. Another was examining the site’s seniority distribution and whether engineers were developing at appropriate rates, rather than only checking each person’s nominal level.',
'The increased scope involved both breadth of people affected and the time horizon of judgment. He presents a collection of such decisions as the promotion story rather than naming one isolated code change or asserting that simply growing a site guarantees the same level.'
],484.8,636.48,speaker='Philip Su')]
b.append({'type':'table','title':'Several ways for senior scope to grow','headers':['Dimension','What Su emphasizes'],'rows':[['Breadth','Coordinate and influence a wider collection of people and decisions.'],['Depth','Solve qualitative technical problems that adding less-senior engineers cannot reproduce.'],['Integration','Combine many kinds of work where a strong generalist matters.'],['Time horizon','Use evidence now to choose actions whose effects arrive much later.']],'evidence':[{'start':6.0,'end':337.68},{'start':554.16,'end':636.48}]})
save(3,'Senior scope grows in depth, breadth, and time horizon','Philip Su explains why the highest engineering levels require qualitative judgment and illustrates that scope through building Meta’s London engineering site.',b,'career',['Closing pointer to the full episode and feedback request at 00:10:38–00:10:48 are omitted.'],kind='companion',notes='Historical headcount examples remain approximate and explicitly stale in the speaker’s account. The three initiating questions are retained, including the coaching distinction when no model senior engineer is nearby.')
b=[qa('Should an engineer organize a career around promotion or around developing useful behaviors and impact?',[
'The guest strongly favors impact over title. In evaluating advancement, he wants to see important outcomes rather than an attempt to negotiate a checklist whose completion mechanically triggers promotion. A person can technically satisfy a stated activity while performing it in a way that adds little value; that leaves the underlying reason for advancement unmet.',
'He also acknowledges a personal reaction: repeated attempts to pin leadership down on rewards can feel transactional and annoying to him. That is his perspective as a leader, not a guarantee that all managers respond alike. His substantive argument is that genuine impact remains what should be recognized.'
],0.0,154.36,speaker='Guest'),qa('How should quieter engineers balance impact with making their work visible?',[
'The host challenges a pure impact-first account: good engineers can be weak at communicating their results and may lose out when promotion decisions depend on people noticing. He distinguishes useful visibility from cynical self-promotion.',
'The guest agrees that visibility matters. Engineers need contact with people who understand important challenges, coordination with collaborators, and recognition of their capabilities so others can entrust them with bigger work. His distinction is the purpose and framing of the communication: making work understandable and coordinating it can lead to different behavior than trying to brag about oneself.',
'Updates should also recognize collaborators and thank the team. That makes the contribution legible without implying only the sender mattered, helps others feel valued, and supports the trust required for leadership. The host observes that two motives can produce superficially similar updates; the guest emphasizes how much the message centers the individual versus the work and other people.'
],154.36,394.08,speaker='Guest'),qa('Does the loud high performer often get promoted sooner than an equally strong quiet colleague?',[
'The host argues that persistent lobbying can win extra attention even when both people have real impact. The guest says outcomes depend on organizational culture and that his own culture tries not to reward that behavior. He admits there are edge cases where lobbying earns consideration simply by keeping someone top of mind.',
'He does not advise abandoning ambition. He wants ambition expressed as a desire for greater impact: ask whether you are working on the most important problem, what you could learn, and where you could contribute more. A hardworking engineer can otherwise spend extraordinary effort on a low-priority task and still miss the outcome they sought.',
'Making those aspirations known and asking for opportunities are valuable conversations. What he opposes is reducing the relationship to contractual boxes followed by a demand for promotion. The debate therefore retains a real tension: the host worries about unequal recognition, while the guest prefers impact-centered visibility and managerial judgment to promotion bargaining. Neither establishes that recognition will always perfectly match contribution.'
],394.08,568.6,speaker='Guest')]
save(4,'Ambition, impact, and the limits of promotion checklists','A host and CTO debate how to make valuable work visible without reducing career growth to a transactional promotion checklist.',b,'career',['Closing full-episode pointer and feedback request at 00:09:12–00:09:28 are omitted.'],kind='companion',notes='The guest’s identity is not established within the clip’s text, so the role label is used. Three initiating questions are preserved; the host’s recognition concern remains distinct from the guest’s impact-first preference.')
