exec(open('books/RyanLPeterman/editorial/worker3-notes/meta25.py').read().split("Path('books/")[0])
qa('Why stay on the same team while many peers changed companies?',[
'Evan enjoyed both the mission and the people. The organization grew so quickly that staying did not mean doing an unchanged job: terrorism work, child-safety work, graphic violence, managers, and colleagues all changed around him. He was not solely optimizing promotions, although the growth was rewarding. Ryan more deliberately evaluated how to grow fastest and repeatedly decided that another clear promotion opportunity, good colleagues, and enjoyable work made staying attractive.',
'Both acknowledge a possible trap in always pursuing a next milestone that feels close. It can postpone broader technical experience elsewhere. Nevertheless, they have little regret about staying through a fast staff promotion: that level improved compensation and made direction-setting and working through others possible, activities they found satisfying.'
],3130.04,3428.72,[fu('Do you wish you had changed environments sooner?',[
'At this point in the conversation Ryan defers the fuller discussion of his recent transition. They agree that a clear, enjoyable staff trajectory made staying reasonable, while recognizing that another environment might have produced broader technical learning. They present that as a tradeoff rather than a universal stay-or-leave rule.'
],3254.8,3428.72)])
qa('What was the anchor story behind the staff promotion?',[
'Evan’s progression took one half year for the first promotion, two halves for senior, and three for staff. During the last stage he led graphic-violence engineering when the Christchurch mosque attack was livestreamed and copies circulated. He describes an emergency response involving integrity leadership and policy colleagues, repeated overnight work, model training, and changes to detection and content-matching systems. He emphasizes the victims and families rather than treating the atrocity as a career opportunity.',
'The response exposed underinvestment in detecting catastrophic events on live video, which differed from screening existing photos and recordings. The company formed realtime integrity around Evan and a product manager and asked them to determine staffing, scope, and a roadmap. Early progress was slow because the events were rare: training on the handful of known cases risked overfitting, and waiting for another tragedy was an unacceptable way to assess the system.',
'His golden-set-recall project curated past examples and built an evaluation environment that replayed videos and comments through real production infrastructure while isolating them from users. It tested the complete path rather than only a model. Evan reports that the initial measured recall for the better-represented suicide examples was roughly nine percent.',
'Looking closely at misses revealed a neglected signal: viewers’ comments often showed they understood the danger before image and audio models did. Adding temporal comment signals raised recall to roughly fifty to fifty-five percent in his recollection, created more detected training examples, and enabled further improvements. He says recall eventually reached the mid-nineties by the time he left, but the staff promotion came earlier, when evaluation and substantial initial improvement had been established. These are his retrospective figures, with some uncertainty in the precise intermediate numbers.'
],3380.16,3871.68,[fu('How large did the new team become?',[
'At promotion time Evan remembers approximately four or five engineers. Realtime integrity later reached roughly twelve to fourteen before splitting into two teams of eight near his departure. Increased investment followed demonstrated progress and sustained attention from senior leadership; the original project was not assumed successful from day one.'
],3831.12,3914.04),fu('Who decided to give you that scope?',[
'He does not know the exact decision maker. At the time he felt he had advocated strongly for the new team after the incident. Later he learned that his manager had done much more advocacy behind the scenes than he appreciated. His own initiative and leadership mattered, but he deliberately corrects a purely self-created-opportunity version of the story.'
],3916.48,4005.72)],speaker='Evan King')
blocks.append({'type':'flow','title':'Making a rare-event detection problem measurable','editorial':True,'steps':[{'title':'Recognize the gap','text':'A crisis exposes weak real-time detection.'},{'title':'Create safe replay','text':'Curate examples and replay the full path in isolation.'},{'title':'Inspect the misses','text':'Measure recall and look beyond the model’s existing signals.'},{'title':'Add a useful signal','text':'Use temporal comments alongside image and audio information.'},{'title':'Improve with feedback','text':'More detections create data for further iteration.'}],'caption':'Editorial synthesis of Evan’s account. Arrows mean the sequence of learning and improvement he describes, not a guaranteed causal recipe.','evidence':[{'start':3559.48,'end':3851.68}]})
qa('Which behavior mattered most in the staff story?',[
'Evan points to trying the simple, obvious solution and keeping the whole problem in view. His multidisciplinary team crossed infrastructure and modeling boundaries, but technically sophisticated researchers could become absorbed in improving the model itself. With less investment in that particular expertise, he focused on what would move the actual detection number. Comments seemed obvious only after the team had been concentrating on pixels, audio, and complex temporal modeling.',
'Ryan describes a similar Instagram compute-efficiency project. He explored video-processing efficiency before pandemic usage made capacity critical. After brainstorming with strong engineers, the best improvement was a comparatively trivial removal of redundant work. He values the ratio of useful impact to time, complexity, and maintenance burden: a simple change with a large effect can beat an elaborate year-long project.',
'They praise the Meta culture they experienced for rewarding realized impact rather than merely implementation difficulty. The practical skill is to identify the important constraint, find what actually improves it, and drive the work even when the solution lacks technical glamour. Their descriptions of reward systems are personal observations of that context.'
],3963.52,4385.68)
qa('Were you acting partly as a manager while still an individual contributor?',[
'Yes. Evan’s role went beyond the usual technical-direction interpretation of tech lead. Engineers still had formal managers who owned promotion decisions, but he helped those managers understand performance, supported teammates’ growth, and participated in relevant discussions. An attempted invitation to calibration was ultimately rejected by a director; he does not know why.',
'He took people leadership seriously, observed his manager, and read a management book when given the graphic-violence team. He believes the arrangement worked because colleagues trusted that he was on their side. He qualifies that judgment rather than claiming to speak for them. Someone who feels competitive, aggressive, or inserted between an engineer and their manager could easily undermine the same arrangement.',
'Because levels were not public on his team, Evan could not rely on a displayed title as authority. He needed to earn credibility through useful technical judgment and supportive behavior. Ryan agrees that influence at staff comes from convincing people who do not report to you that the direction is sound and that they can trust you.'
],4369.8,4768.88,speaker='Evan King and Ryan Peterman')
qa('Did you consider switching from the IC path into management?',[
'Evan expected to reach staff and then become a manager, but a plausible IC7 path appeared while he had broad organizational context, senior-leadership visibility, and interesting cross-organization projects. Conversations with friends who had become managers also revealed the weight of directly owning people’s issues. He considered reaching IC7 first and perhaps later moving into a more senior management role.',
'Ryan faced a similar choice. His manager saw a clear continuation to IC7 but warned that management advancement depended more on organizational opportunity. Ryan nevertheless chose management to learn a different set of behaviors and preserve options for the longer term. He worried that a very senior IC career could become specialized to a handful of huge companies, with influence and compensation tied to internal credibility and equity.',
'Both describe these portability and compensation concerns as their reasoning, not a claim that senior IC skills have no value elsewhere. A fast internal progression may not transfer to an equivalent external title, and rebuilding trust takes time.'
],4768.88,5078.52,[fu('What is a tech-lead manager?',[
'Ryan first moved into a role he describes approximately as seventy percent IC and thirty percent manager, with a small team focused on a narrow technical area. Contributions were still assessed primarily as IC work. He later moved toward conventional organizational leadership after deciding he wanted to grow further as a manager.'
],4901.08,4969.16),fu('What has been the biggest learning from management?',[
'Ryan’s manager had been right about the career dependence: advancement became more closely coupled to team and organizational growth. Moving during an efficiency-focused period reduced that opportunity. He also found the work shifted toward people problems and a solid block of daytime meetings. As an IC he could arrange fragmented meetings and complete technical work later; as a manager, much of the job requires other people being available. Review season adds substantial writing after those meetings.'
],5032.84,5225.96)])
qa('What led you to leave Meta after reaching staff?',[
'Evan remained for more than a year and a half after staff and was working toward IC7 with a new manager who treated him as a partner in growing the team. A former manager whom he deeply respected began discussing crypto and Web3 ideas with him outside work. Evan had related interests from college, and together they built a product that attracted roughly ten thousand users quickly.',
'His collaborator was ready to pursue startups; Evan had expected to stay on the corporate path and initially wanted funding before leaving. Eventually the side project became more compelling than his day job. He found himself waiting for work to end so he could return to those problems, and the chance to build with a trusted partner outweighed the attractive promotion and equity path. He left before funding, acknowledges periods of regret afterward, and says that in hindsight he does not regret the decision.'
],5185.96,5474.08,[fu('What tipped the decision despite a very lucrative potential path?',[
'The cofounder did not pressure him. Evan describes a change in intrinsic motivation: the after-hours work had become what he most wanted to spend time doing. Some early traction and a trusted partnership mattered, but there was no fully secured financial result at the moment of departure.'
],5390.92,5474.08)],speaker='Evan King')
qa('What happened across the startup experiments?',[
'The first venture combined social activity around crypto with on-chain activity to create rankings and predictions. Evan reports roughly one hundred thousand users, fundraising, and acquisition interest. They sold around a market downturn, then faced a new question: what should this partnership build next?',
'Over six to eight months they tried many unrelated ideas. One product copied a website into editable Figma frames; technically valuable reverse engineering, mostly credited to his cofounder, led another company to buy the technology. Evan describes these as two acquisitions with some looseness about the term, not two identical company outcomes.',
'They eventually returned to an area they knew and cared about: interviewing and hiring. Initial AI mock interviews did not work particularly well. Human mock interviews offered to gather training data produced repeated requests to pay for more of the human sessions. After initially resisting that direction because they wanted to build technology, they followed what users valued. Hello Interview grew from that demand, later adding better AI-guided learning and educational resources.'
],5476.2,5745.6,speaker='Evan King')
qa('Had the startup path financially outperformed staying in big tech?',[
'Not at the time of the conversation. Evan explicitly distinguishes realized monetary compensation from the value of experience. He believes the technical breadth, learning habits, and company-building skills will improve his lifetime opportunities, but that future payoff is his optimistic forecast rather than an accomplished result.'
],5696.24,5789.48,speaker='Evan King')
qa('What did startups teach that your Meta role had not?',[
'Leaving humbled Evan. His rapid promotions and broad team leadership had given him confidence, but he discovered large practical gaps. At Meta, he could change a narrow component and rely on an enormous surrounding organization to deploy it to billions of users. That did not mean he had independently learned to configure a database, create a cache, stand up a product, or build a front end.',
'In the startup he had to learn these pieces while delivering. He now feels more able to enter an unfamiliar situation and work out what is needed. Ryan mentions a counterview from another engineer: startup setup work can feel technically routine compared with deep specialist problems inside a large company. They therefore distinguish breadth from depth rather than asserting that all startups teach more in every way.',
'Evan thinks learning broad foundations first could make later specialized optimization more meaningful, while hesitating to recommend that order as the best career strategy. He also wishes he had used his time at Meta to investigate abstractions he consumed every day and read the engineering explanations that were available around him. Curiosity could have made more of the large-company environment without requiring a job change.'
],5790.84,6049.72,speaker='Evan King and Ryan Peterman')
qa('How should a big-tech engineer judge when to try a startup?',[
'Evan recalls posting enthusiastic startup advice and being criticized for ignoring his own advantages. He was financially secure and did not have a family to support, which made unpaid risk possible. He now insists that personal circumstances determine what is feasible. His enthusiasm for faster learning cannot substitute for that judgment.',
'For a new engineer already in big tech, he would generally learn enough organizational and interpersonal foundations to reach senior before leaving. Someone who can afford the risk and prioritizes breadth might consider a move sooner; a later-stage startup can be an intermediate step before founding. These are his recommendations from his experience, with explicit financial and family qualifications.',
'They also note that contemporary AI coding tools helped their two-person company ship substantial work quickly. Evan acknowledges that such tools can help or slow particular tasks but does not develop a general tool prescription in this interview.'
],6049.72,6222.64,speaker='Evan King')
qa('Which periods produced the greatest skill growth?',[
'Evan identifies the startup period, even relative to the steep learning at the start of his career. It was stressful, uncomfortable, and sometimes emotional, and he credits his partner’s patience. His positive assessment rests on having come through that period, not on pretending it felt easy while it was happening.'
],6224.96,6267.2,speaker='Evan King')
qa('How many hours were you working at Meta and in startups?',[
'Evan realizes that saying he did not work much at Meta understates informal work. He usually arrived around eight or eight-thirty and left around five-thirty or six, then sometimes checked experiments, made tweaks at home, or woke to see whether a model-training run had completed. It exceeded an ordinary forty-hour week, although he also left early for weekly snowboarding and usually did not treat weekends as compulsory work.',
'The first startup was much more demanding. He was both learning foundations and supporting a fast-paced realtime analytics product where failures mattered financially to users. Days could run from morning until midnight or two, and he carried a laptop even to a friend’s birthday because an incident might fall to him alone. Hello Interview later became steadier; he still worked more than at Meta but could attend social events without carrying the laptop. The business’s incident profile changed the experience as much as the startup label did.'
],6268.88,6446.8,[fu('How does that fit with your advice about work-life balance?',[
'Near the end of Meta, Evan had considered two broad ways to live: make work a central source of passion and fulfillment, or do a strong bounded workday that financially supports interests and relationships elsewhere. He thought he might adopt the latter after another promotion. Founding instead returned him to a passionate work-centered period. He admits the apparent contradiction and sees the quieter option as a possibility later rather than claiming he had already achieved it.'
],6448.96,6539.24)],speaker='Evan King')
qa('What is your biggest career regret?',[
'He wishes he had slowed down to understand why things worked. Iterating until a metric improved or a system functioned could produce immediate impact without building a durable explanation. The same shortcut appeared during early startup pressure: once something worked, he moved on.',
'As the company stabilized, he could finish required work with time left over and use that margin for reading engineering explanations and investigating underlying libraries and platforms. He sees a tension in an impact-oriented culture: it can reward shipping and moving on even when understanding the abstraction underneath would improve the engineer’s long-term foundation. He would keep the useful drive for impact while adding that inquiry.'
],6535.96,6725.0,speaker='Evan King')
qa('What would you tell yourself when graduating?',[
'Invest in friendships, romantic relationships, and life outside work with some of the deliberateness given to career goals. Evan had roadmaps and frequent checks for professional growth but applied much less effort to broader life. Moving to Los Angeles and making more friends outside the technology bubble helped him value mutual investment and everyday support.',
'He now finds those relationships a major source of fulfillment alongside continuing work. This is not only an hours-allocation lesson: even when there was time, he had not recognized what deserved deliberate attention.'
],6703.04,6877.08,[fu('Would you accept slower promotion in exchange for stronger relationships?',[
'Given a strict choice, yes: he would prioritize relationships. But he rejects the premise that he actually had to choose. He believes he had enough time to build both and simply did not invest enough in relationships or understand their importance yet.'
],6792.76,6877.08)],speaker='Evan King')
blocks.append({'type':'paragraph','heading':'A final nuance about interview preparation','text':'During the closing promotion, Ryan mentions a roommate who was initially overconfident in system-design interviewing because he already designed systems at work. The useful lesson is that an interview is a particular format that may require targeted practice; professional seniority alone does not ensure performance. The service endorsement itself is omitted.','evidence':[{'start':6976.48,'end':7030.56}]})
s=json.load(open('books/RyanLPeterman/editorial/worker3.json'))['sources'][0]
section={'id':s['id'],'source_id':s['id'],'title':'Rapid growth, broader learning, and the costs of chasing the next rung','kind':'interview','deck':'Evan King and Ryan Peterman compare fast staff-engineer paths, showing how initiative and support create growth and why a successful ladder can still leave gaps.','blocks':blocks,'related':[],'omissions':['Opening trailer at 00:00–00:39 repeats later material and is not counted as question rounds.','Closing product and channel promotion at 01:54:39–01:57:13 is omitted except for the substantive distinction between professional system design and interview preparation.']}
result={'section':section,'coverage':{'source_id':s['id'],'sha256':s['sha256'],'reviewed_chunks':list(range(1,13)),'status':'included','reason':'Read all twelve compact chunks in full; the interview, ordered follow-ups, qualifications, and substantive closing preparation point are preserved.'},'editorial':{'theme':'career','question_rounds':sum(b['type']=='qa' for b in blocks),'followup_count':sum(len(b.get('followups',[])) for b in blocks),'notes':'Mutual interviewing is retained with both engineers’ experiences distinguished. Self-corrections about managerial advocacy, retrospective metric uncertainty, unrealized startup earnings, personal risk capacity, and relationships are preserved. The precise recalled date of the Christchurch attack and the uncertain college adviser name are not reconstructed.'}}
Path('books/RyanLPeterman/sections').mkdir(exist_ok=True)
Path('books/RyanLPeterman/sections/'+s['id']+'.json').write_text(json.dumps(result,indent=2))
