import json
from pathlib import Path
blocks=[]
def qa(q,a,start,end,followups=None,speaker='Evan King and Ryan Peterman',takeaway=None):
 d={'type':'qa','question':q,'speaker':speaker,'answer':a,'evidence':[{'start':start,'end':end}],'followups':followups or []}
 if takeaway:d['takeaway']=takeaway
 blocks.append(d)
def fu(q,a,start,end,speaker='Evan King and Ryan Peterman'):
 return {'question':q,'answer':a,'speaker':speaker,'evidence':[{'start':start,'end':end}]}
qa('Did fast career growth require starting programming as a child?',[
'Evan encountered computer science in a high-school AP course near Seattle. Classmates with Microsoft-employed parents seemed far ahead of him, and the subject initially threatened his identity as a straight-A student. He worked hard enough to succeed but did not enter college determined to study computer science. In an introductory engineering course, his small head start suddenly made him feel capable relative to beginners. Enjoyment followed that experience of competence.',
'Ryan had no AP computer-science course and did not know what the field was until UCLA. He entered engineering undeclared, chose electrical engineering because he liked computers and games, and switched to computer science and engineering in his junior year when he understood its employment path better. Overlap in the degree requirements allowed him to reuse earlier coursework. Neither presents his later progression as evidence of childhood programming genius.'
],83.12,264.12)
qa('Why start a college hacking club, and what did it teach?',[
'Evan played Division I soccer at Cornell until his junior year. The training, early workouts, and weekend travel consumed time, yet he knew he intended to become a software engineer rather than a professional player. Quitting created room for building things. After participating in capture-the-flag competitions with teams found online, he recruited locally with flyers, assembled founding officers, and grew a core competition team of roughly 25 people; some weekly teaching sessions attracted as many as 200.',
'The club combined technical practice, friendships, and teaching. Evan remembers peers who were stronger technically than he was, and he learned by building sophisticated projects with them. Ryan connects organizing, recruiting, communicating, and aligning people with the work of senior engineers. A leadership role can have lasting value beyond improving an application, especially when the activity itself is enjoyable.'
],264.12,434.72,[fu('What made your own side projects useful?',[
'Ryan built a Raspberry Pi service to indicate whether his engineering club’s lab was open. Because an officer had to be present, the service watched the lab Wi-Fi for known officer-device MAC addresses and let students query a Slack bot for current presence. It solved a real problem and gave him a concrete interview story.',
'They recommend noticing problems nearby and writing software that people actually use. A project chosen from a generic list may still provide practice, but without users it resembles another class assignment and misses the learning involved in taking a useful solution all the way through delivery.'
],431.16,567.0)])
qa('Did competitive hacking make the hiring interviews easy?',[
'Evan found algorithm interviewing difficult at first and spent many hours practising with classmates. His successful Meta campus interview included a hard problem whose trick he had skimmed the previous evening. He believes that lucky encounter mattered materially: without it, the rest of this career path might never have happened.',
'Ryan also struggled despite spending most of his Bloomberg internship’s spare time practising. His assigned project took only a small part of the summer, but intensive preparation did not prevent him from failing his later onsite algorithm interviews. He finished with a Bloomberg return offer and an Amazon offer obtained through an unusual campus logic-test format. He chose Amazon partly to remain on the West Coast.',
'Evan recalls badly misreading a Palantir interview: being released early was described as compatible with either exceptional success or failure, so he waited confidently for an offer and was devastated by rejection. Their comparison of then-prestigious employers—Palantir, Quora, Jane Street, and other finance firms—is a recollection of their college hiring environment, not a current ranking. The larger point is that preparation, expectations, and luck all influence entry opportunities.'
],565.44,934.4)
qa('How did you choose your first Meta team?',[
'Meta’s boot camp let Evan try tasks for several hiring teams before making a mutual choice. He had expected to join cybersecurity after years of hacking, but the particular teams he met felt less welcoming than he wanted. Content integrity offered machine-learning problems, a mission he found meaningful, and colleagues he related to. He joined a terrorism-content team being established in Seattle, initially with a manager shared across teams and a part-time technical lead.',
'Ryan selected Instagram infrastructure with much less understanding of the long-term tradeoffs than he has now. He then associated product work with front-end work and infrastructure with technical depth, assumptions he now calls mistaken. Instagram felt exciting, and when the preferred manager lacked headcount, Ryan made an earnest case for joining until the manager found flexibility. Both see agency as a way to convert available opportunities into a better fit; good opportunities may require actively seeking them.'
],934.4,1319.28,[fu('Where did boot camp happen, and did you deliberately choose a technical stack?',[
'Evan split boot camp between two two-week stays in Menlo Park and time in Seattle. He gravitated toward backend work without an elaborate stack-selection strategy. Ryan thought more explicitly about product versus infrastructure and which product organization to join, although he stresses how incomplete his knowledge was as a new graduate.'
],1047.72,1224.04)])
qa('What was surprising about onboarding into content integrity?',[
'Evan’s early encounter with a colleague’s monitor displaying explicit content was jarring because it was plainly part of an ordinary working day. The team’s task required examining material that would be extraordinary in most offices; over time, colleagues became accustomed to that exposure. He remembers the team sitting out of the way in the Seattle office, and colleagues said that arrangement reduced accidental exposure to disturbing content. His story is about the unusual context of moderation engineering, including material more troubling than the initial anecdote.'
],1321.72,1445.68,speaker='Evan King')
qa('What did the terrorism-content system actually do?',[
'Evan describes Estuary, a backend system largely written in Hack, as a staged content-processing funnel. Cheap initial checks determined whether content warranted expensive model evaluation. Photo matching, model scores, thresholds, and combinations of human reviews fed an eventual action. The infrastructure made it easier for the team to swap models, adjust thresholds, and run experiments rather than hard-code a single moderation path.'
],1445.68,1538.04,speaker='Evan King')
qa('Was the first promotion something you negotiated with your manager?',[
'Evan’s first promotion arrived after roughly his first half year and was a surprise. He thought he was doing good work but had not discussed promotion or calibrated himself against colleagues. The manager’s praise, promotion announcement, and compensation change became a major confidence-building moment. He does not recommend relying on that kind of surprise.',
'An earlier Zillow internship had supplied another important boost. He completed the assigned work quickly, pursued interesting additional work, and received a return offer and unusually strong praise from a manager with substantial experience. That external confidence helped him enter Meta, although it did not instantly eliminate all insecurity.'
],1538.04,1682.52,[fu('Had you interned at Facebook first?',[
'No. Evan had interned at Zillow. His memories of that internship and the first Meta promotion illustrate how specific encouragement from experienced managers helped him believe he was capable.'
],1579.36,1660.48)],speaker='Evan King')
qa('What did those managers see in you so early?',[
'Evan identifies curiosity and an unwillingness to treat the assigned task as the boundary of his job. At Zillow, after finishing his rental-team work, he turned posters about locking unattended computers into a playful internal security game. Colleagues could record an unattended machine, and leaderboards and graphs encouraged participation. Spending time with security colleagues eventually led to attending Defcon with them, despite security being outside his team’s charter.',
'He describes a similar pattern at Meta: completing the requested implementation created time to improve it and explore adjacent ideas. He frames this as pursuing useful, interesting work rather than merely doing extra work for its own sake.'
],1663.84,1742.24,speaker='Evan King')
qa('How did you finish assigned engineering work fast enough to explore more?',[
'Evan initially resists claiming a simple secret, because the reputation for speed feels more grand than his conscious process. Ryan describes deep familiarity with a code area, a practiced editing-and-review workflow, and enough repetitions to know exactly where a requested change belongs. At one coding-heavy period he remembers submitting about ten diffs a day. He also worked very long days and acknowledges that adding working time is one way to create an extra budget for growth.',
'Evan kept searchable notes whenever he solved a problem so he would not have to solve it from scratch twice. He also became comfortable investigating a blockage for roughly an hour, finding the person who knew the area, asking a focused question, writing down the answer, and continuing. Ryan emphasizes that a well-timed question can save days of blind searching, dwarfing small editor optimizations.',
'Both highlight code search as a lasting skill. In a large monorepo, someone has usually solved a similar problem already. Guessing likely function or variable names, finding the analogous implementation, and understanding the surrounding context accelerates junior execution and later work on ambiguous cross-system problems.'
],1743.52,2140.36,[fu('Does working extra only make sense if you enjoy it?',[
'They distinguish the experience of being absorbed in enjoyable work from forcing long hours on work one hates. Ryan enjoyed the novelty and growing fluency; Evan stresses that advice about extra hours becomes dangerous when detached from that motivation. The time-budget explanation describes their experience, not a claim that everyone should work those hours.'
],1888.96,1968.08)])
qa('What changed between the midlevel and senior promotions?',[
'As content integrity expanded, the initially tiny terrorism team acquired senior engineers and eventually split across terrorism, child-exploitation imagery, and graphic violence. Because Evan had arrived first, he held useful context and helped newer colleagues ramp up regardless of their formal level. His manager offered him responsibility for an underinvested graphic-violence area with a junior engineer and a research scientist.',
'He began setting weekly meetings, shaping the roadmap with management, and holding one-to-ones with teammates. The team improved its detection precision and recall, although he does not remember figures well enough to quote them. Guiding other people and improving a neglected area supplied the senior-level story; the informal tech-lead label mattered less than the responsibilities.',
'Ryan’s corresponding experience emerged when a cross-client/backend workstream grew around an area he understood deeply. He sometimes felt stretched while leading meetings but did the work anyway. An unusually capable intern showed him that entrusting execution to another person could free him for more scope. Evan similarly needed repeated managerial feedback before delegation clicked: doing everything quickly himself would eventually cap what the team could accomplish.'
],2140.36,2901.52,[fu('Why did the manager trust someone so early in their career?',[
'Evan credits a strong manager who noticed potential, provided a larger challenge, and coached him through it. The preceding evidence was not just tenure: Evan was helpful in onboarding and willingly answered colleagues’ questions. His knowledge became useful to other people, which made expanded responsibility more plausible.'
],2305.56,2472.52),fu('Did being the original owner create territorial feelings when senior engineers arrived?',[
'Yes. Evan initially felt protective of his work when a technically strong senior engineer joined. He recognized that response, discussed it with his manager, and opened himself to the engineer’s feedback. Reviews and design discussions then became a major source of technical growth, and the colleague became a lasting friend.',
'Ryan recalls senior collaborators similarly improving his documents and projects. He did not know exactly how each person’s performance review divided the credit, but the collaboration produced better work and learning. They advise treating shared scope as an opportunity for growth rather than assuming someone else’s contribution diminishes one’s own.'
],2504.0,2681.84)])
qa('By the senior promotion, were you openly discussing promotion goals?',[
'By then Evan and his supportive manager discussed target timing, requirements, and what still had to happen. Friends from his boot-camp cohort often lacked equally active advocacy. His advice is to state the desired next level and timing, ask whether the manager agrees with the plan, and surface gaps early—even if that feels vulnerable. Hearing bad news before review season is more useful than an unpleasant surprise afterward.',
'Ryan’s manager was supportive but did not proactively drive promotion dates, so Ryan repeatedly asked what the next level required and advocated for his growth. He sees strong performance and explicit discussion as mutually helpful: the manager has reason to invest in an engineer whose broader contribution helps the team. Evan later adopted more self-advocacy himself. They recognize luck in getting a capable, aligned manager and the engineer’s responsibility to make goals visible.'
],2903.28,3099.08)
Path('books/RyanLPeterman/editorial/worker3-notes/meta25-part1.json').write_text(json.dumps(blocks,indent=2))
