from write_section import *
b=[]
b.append(qa('What work led to your senior-engineer promotion at Meta?',[
'Cherny recalls a project connecting Messenger chats with Facebook groups, after several earlier attempts to bring the products closer. The product hypothesis was that interaction was moving from public social spaces toward more casual, real-time conversation. He picked up a PM’s idea, built an early version, then recruited a few engineers and design and data-science support as it showed promise.',
'The small team did work beyond coding. Without dedicated user research, they showed features to cafeteria workers and watched whether they could accomplish tasks without much prompting. He taught teammates the same method. The rough early experience still helped test whether the core idea worked.',
'He values that generalist approach at Anthropic too: engineers with product sense, design interest, and willingness to speak with users, plus other functions willing to code. His own background in small companies taught him to own the whole outcome. He says the initial half brought his promotion and the next half brought promotions for the rest of the early engineering team.'
],60,339.6,speaker='Boris Cherny'))
b.append(qa('What is latent demand, and why does it matter?',[
'Cherny describes it as existing user intent expressed through a product not designed for that purpose. People were already buying and selling in Facebook groups; dedicated commerce groups and later Marketplace made that behavior easier. He cites observed proportions of group posts as an example of the signal, rather than as current measured usage.',
'He offers profile-view behavior as another hypothesized signal behind dating features. The broader principle is to notice what users are already trying to do, especially how they bend a flexible product, then reduce friction around that intent. His claim that a product cannot make people do something they do not already do is deliberately strong product philosophy, not a proven universal limit on innovation.'
],339.6,426.8,speaker='Boris Cherny'))
b.append(qa('How do you work across organizations with very different cultures?',[
'His Facebook product team prioritized rapid releases and engagement, while Messenger prioritized reliability and performance. The clash was built into goals, incentives, and organizational design, not just personalities. Messenger engineers had reason to fear changes that would damage the metrics they were responsible for.',
'He believes a version of the project failed partly because the benefit was much clearer for Facebook than for Messenger. Find a goal, hypothesis, or interest that both groups can genuinely share; simply expecting collaboration despite divergent rewards is weak.'
],426.8,548.24,followups=[fu('What would you change if you could revisit that project?', 'He would seek an organizational arrangement with a closer common manager and better-aligned incentives, potentially bringing Messenger into the Facebook organization for the effort. He is describing a hindsight proposal, not a reorganization he carried out then.',548.24,582.08)],speaker='Boris Cherny'))
b.append(qa('How did side projects such as Undux affect your career?',[
'He values curiosity outside one’s main assignment, even when the interest is not technical. Undux began because he found React state management unnecessarily difficult and wanted a simpler approach. A nonprofit used his early library; at Facebook he recognized that repeated support questions reflected the same problems he had encountered.',
'An initial announcement brought some users but did not by itself drive broad adoption. He grouped support complaints by team, contacted each team’s leadership, and gave many focused technical talks. Meeting users where their specific pain already existed worked better than expecting a general post to persuade everyone. He recalls it becoming widely used before newer tools replaced it.',
'Other side explorations included a TypeScript book and a meetup. The book consumed roughly a year and he does not lightly recommend that commitment, but it let him go deeply into the language. Meeting prominent JavaScript creators also made ambitious work feel more accessible: they were people building things, rather than an unreachable class of geniuses.'
],582.08,884.64,followups=[fu('Did the state-management project help in performance review?', 'He thinks it appeared, but calls it a bonus rather than the work that alone earned the next level. Its larger value included learning, relationships, and useful experience with adoption.',790,805)],speaker='Boris Cherny'))
b.append(qa('Did that language knowledge prove useful in later work?',[
'He describes an unusual start to language exploration: a motorcycle accident injured both arms, making coding difficult. He experimented with languages requiring fewer keystrokes, including CoffeeScript and Haskell, then a colleague introduced him more deeply to Scala and functional programming.',
'Functional Programming in Scala is the technical book he says most changed his thinking. He recommends the way it teaches problem solving even to people who may never use Scala. The lasting idea is to think in types and pay attention to signatures as a guide to clean structure.',
'That habit transferred across Flow, Hack, Python, and TypeScript in his later jobs. He distinguishes the mental model from the particular syntax used at a given company.'
],885.12,1024,speaker='Boris Cherny'))
b.append(qa('Why do you think entering Meta underleveled was fortunate?', 'Lower expectations gave him space to explore and build things without immediately satisfying a larger set of project and people requirements. The host suggests that exceeding an initially lower bar can also create momentum and a strong first impression; Cherny agrees. He sees a downside to seeking a higher title at every move if it raises pressure before the person understands the new organization. This is his personal benefit from one circumstance, not a universal recommendation to accept lower compensation or responsibility.',1025.6,1136,speaker='Boris Cherny'))
b.append(qa('What work led to the staff-engineer promotion?',[
'He wanted a better JavaScript-based web experience for Facebook groups, which still relied heavily on PHP with fragmented interactive state. Leadership initially resisted because supporting infrastructure was not ready. When the broader Facebook desktop rewrite, Comet, began, he offered groups as an early customer and helped argue that participating would let the team get ahead of required migration work.',
'The effort grew from an initial group of roughly a dozen engineers into a substantially larger migration. By helping build the platform rather than merely consume it, his product team could shape abstractions other teams would later use.',
'One example involved optimistic button updates and server responses arriving out of order. He built queuing around mutations to preserve consistent state. He recalls choosing a consistency tradeoff suited to the problem, and the shared work built relationships with the infrastructure team. His broader lesson is that product engineers can go a layer deeper into infrastructure and infrastructure engineers can talk to users.'
],1136,1372.24,followups=[fu('What additional opportunities came from being early?', 'Besides shared infrastructure, the team helped define what product quality should mean on the new platform. Cherny wrote notes and gave talks about lessons others could reuse. Getting ahead of the migration gave the team a chance to set standards rather than only comply with them.',1373.36,1444.32)],speaker='Boris Cherny'))
b.append(qa('How many people would that migration require with contemporary coding agents?', 'Cherny revises the original scope to perhaps 20–30 engineers over about two years, then guesses that tools at the time of the interview might support roughly five engineers over six months. He imagines parallel agents building changes and using browser feedback to refine the interface. He explicitly warns that the estimate could change in three or six months, perhaps radically. These are speculative comparisons, not measured results from rerunning the same migration.',1444.32,1518.96,speaker='Boris Cherny'))
b.append(qa('Why did you joke that VPs usually pick the middle of three options?', 'It was deliberately tongue-in-cheek. He thinks a distant decision maker wants evidence that the team explored options and tradeoffs, while also wanting to contribute a decision. A middle option can provide that. He qualifies the observation: some leaders investigate for themselves, and leaders differ in how much they trust teams. The “80%” framing is a joke from his story rather than a reliable statistic or a reason to manipulate every review.',1520.08,1599.68,speaker='Boris Cherny'))
b.append(qa('How did reporting to a very senior manager affect your opportunities?',[
'Cherny treats this as company-dependent. At Meta, access to leaders could help an engineer find scope and navigate an impact-focused review system. At Anthropic, he sees highly senior people reporting to line managers, so reporting level says less about authority or capability.',
'He also likes common titles because they make it easier to do useful work outside a narrow role. He describes Meta engineering titles and Anthropic’s broader member-of-technical-staff convention as supporting that culture.'
],1599.68,1738.32,followups=[fu('Do common titles make it harder for another team to know how seriously to take you?', 'Yes, but he thinks the upside is stronger: people must earn trust rather than assume a prior title gives them authority in a new setting. Everyone deserves respect, yet authority over a particular decision still requires evidence and relationships. He recognizes the lost shorthand and considers it an acceptable tradeoff.',1738.32,1778.96)],speaker='Boris Cherny'))
b.append(qa('How did you scope work for hundreds of engineers?',[
'Cherny recalls a large investment in Facebook groups as a community platform, leaving leaders to determine what newly allocated engineers would do. He produced many rough scoping documents with options and staffing estimates. In hindsight, he would have added people more gradually as specific products found fit: solving users’ problems is not made easier simply by distributing a huge allocation all at once.',
'A difficult groups-and-pages data-model problem stalled despite senior involvement. He brought technical leads into a short architecture exercise, split them into two groups, and gave both the same requirements. After a few hours, the designs overlapped substantially. Agreement showed where execution could begin; differences exposed risks to investigate with small technical spikes.',
'This let the team stop treating the whole problem as unknowable. The exercise created a concrete comparison without requiring one person to understand every detail in advance.'
],1779,2008.64,followups=[fu('Did people accept the unusual design competition?', 'He scheduled it and made it appealing as an engineering problem. He thinks a leader sometimes needs to act to create a process through which consensus can form, while at other times acting without consensus would be wrong. Here the uncertain path made convening people useful.',2009.92,2059.6)],speaker='Boris Cherny'))
b.append(qa('What helps a technical lead produce a quick scope?', 'Start at a high level and time-box the initial pass rather than disappear into unlimited detail. Cherny suggests roughly half an hour for a very rough view, or a few hours when code investigation is needed. Identify experts and show them a strawman instead of only asking open-ended questions; a concrete proposal makes feedback easier. He now sees coding agents as another way to explore relevant systems, but that is a tool-assisted extension of the same need to expose a reviewable first plan.',2060.8,2149.76,speaker='Boris Cherny'))
b.append(qa('What made the public-groups project a senior-staff-level challenge?',[
'The visible change sounded simple: allow people to read, and in some cases comment in, public groups without first becoming approved members. The downstream changes were much harder. Following without reciprocal approval raised questions about how to represent membership, what admins needed, and how to handle more spam.',
'A senior engineer argued for separate data-model representations, and the team undertook a lengthy migration. Cherny also used a simple simulation of comment quality and spam to make moderation risk concrete, helping bring an integrity team into comment ranking. The work involved many experienced engineers whom he initially felt awkward directing because they shared his nominal level.',
'After auditing many call sites, he concluded the migration had mostly added branching without changing substantive logic. The old member field could support the needed behaviors. He pushed to reverse the migration, asking the senior engineer with the most context to help undo it. That engineer accepted the evidence and later supported Cherny’s leadership. The reversal was costly but reduced confusion for future developers.',
'His eventual judgment is that level does not reliably determine who has the best result. The achievement was not simply leading a large migration; it included recognizing when its premise was wrong and earning the trust to correct it.'
],2149.76,2470.96,speaker='Boris Cherny'))
b.append(qa('How can a strong technical disagreement improve rather than damage a relationship?', 'Earn trust first. Cherny initially disagreed but committed to implementing the senior engineer’s decision, then developed evidence and showed technical judgment. A relationship in which both people know you will execute honestly makes later pushback easier to hear. His recommendation is to invest in that trust before assuming a correct argument alone will carry the disagreement.',2473.2,2522.56,speaker='Boris Cherny'))
b.append(qa('How did you deal with imposter syndrome while leading strong peers?', 'He says not to assume that others at any level have everything figured out. His confidence did not arrive in one dramatic moment; it grew with experience. He regards some discomfort as a possible sign of stretching into unfamiliar work. This is encouragement grounded in his trajectory, not a complete technique that instantly removes anxiety.',2523.36,2562.16,speaker='Boris Cherny'))
b.append(qa('When should an engineer fill a product-management gap versus ask for more PM support?',[
'Understand the decision maker’s tradeoffs before arguing for a preferred answer. A project may be hard to hire for, PMs may be needed on something more important, or an organization may have spare PM capacity that could sensibly be reassigned.',
'The same request therefore means different things in different settings. Think about what leadership values, what work your request displaces, and whether the proposed allocation helps them succeed. He does not give a universal rule that engineers should always absorb another function’s work.'
],2563.92,2704.96,speaker='Boris Cherny'))
b.append(qa('How do you find useful engineering opportunities and give them to others?',[
'He looks for repeated friction in his own coding and asks how to eliminate it. During review he kept a list of recurring comments with examples; once the same issue appeared repeatedly, he wrote a lint rule rather than continue to police it manually. Automation freed his own time and could improve work for many engineers.',
'He did basic validation on ideas, then connected engineers who wanted those opportunities. He thinks understanding their goals is better than simply ordering them to do a project. At Meta, better-engineering work helped an evaluation dimension many people struggled to demonstrate, so a useful project could meet both a system need and an engineer’s growth goal.',
'He also warns that prolonged distance from code weakens a technical leader’s intuition. Hands-on experience anchored the opportunities in actual constraints. His very large approximate count of people involved in side projects is a recollection, not a precise audit of his personal influence.'
],2704.96,2918.32,speaker='Boris Cherny'))
b.append(qa('What is a concrete way to source repeated, high-value side projects?', 'He gives large-data testing as an example. Ordinary tests did not cover a group with millions of members, a highly followed profile, or a very large event, so scale failures appeared only in production. Seeing the same pattern across products, he proposed infrastructure for creating and testing large objects; another engineer took it on and recruited help. The pattern is to notice recurring pain, check whether others share it, and build an abstraction that prevents a whole class of incidents.',2919.68,3044.88,speaker='Boris Cherny'))
b.append(qa('Why did you move from Facebook groups to Instagram in Japan?',[
'The move began with his partner’s dream job in rural Japan rather than a calculated promotion strategy. He tried several internal arrangements, but sponsorship or organizational rules blocked the earlier options. An engineer building the Instagram Tokyo office offered a workable path.',
'He joined despite having scarcely used Instagram, then came to value its emphasis on craft, human experience, and simplifying products as well as measuring them. The new setting taught him different habits from the Facebook organization he knew.'
],3045.36,3193.92,speaker='Boris Cherny'))
b.append(qa('What does “unshipping” mean?', 'Features compete for limited screen space and attention. Adding something useful to a small group can clutter the experience for the majority who do not use it. Cherny describes requiring a usage bar and deleting a feature that fails it, accepting that some users will be disappointed. His argument is about the opportunity cost of accumulated features, not that every low-usage feature lacks strategic value in every product.',3194.64,3258.08,speaker='Boris Cherny'))
b.append(qa('How did you rebuild credibility in a new organization from far away?',[
'Leaders and colleagues helped him connect with people working on code quality and technical debt, but he still had to earn trust. He spent early weeks meeting people, mapping goals and the organization, and writing code to understand the codebase.',
'The severe time-zone gap made meetings difficult, but unexpectedly restored time for coding after years of documents and conversations had left him unhappy. He says he still avoids standing one-on-ones. That made it possible to do work others wanted done but could not fit around their obligations.',
'He explored migrating parts of Instagram’s Python environment toward Hack and Meta’s infrastructure. He considered the original simple choice sensible at small scale but less suitable after years of product growth and a much larger engineering group. This is his contextual assessment; his praise of the alternative serving stack is not a universal language ranking.',
'He began with the people most likely to disagree, building personal trust before debating the migration. Supporters who had been reluctant to speak then joined the discussion. In a product-led organization, creating space for an engineering-led investment required those relationships as well as technical scope.'
],3260.4,3615,speaker='Boris Cherny'))
b.append(qa('When did you delegate the large migration, and how did you decide to trust another lead?', 'Cherny saw a colleague closer to the relevant organization as an excellent owner. He recommends delegating something you understand and care about so you can judge progress, rather than treating delegation as a way to dump disliked work. He cites High Output Management as an influence. Check more at first and less as evidence of reliability grows; with a proactive and technically strong lead, he needed little intervention. The handoff matched the project’s needs rather than preserving personal ownership for its own sake.',3615,3715.52,speaker='Boris Cherny'))
b.append(qa('What happened around the principal-engineer promotion?', 'His manager proposed putting him up for IC8, and he agreed. He had not been campaigning for it. He credits the manager’s willingness to notice readiness and advocate for people, with large modernization projects providing the context. He does not offer a detailed promotion packet or claim that a simple conversation alone caused the result.',3715.52,3748,speaker='Boris Cherny'))
b.append(qa('Did levels guide how you sought more impact and leverage?',[
'Cherny sees levels as company tools for communicating expectations, comparing people in reviews, and planning costs. His own motivation was interesting problems, useful products, and making people’s experience better, rather than the next level itself.',
'He pitched ideas from his earliest weeks as IC4; several were rejected and one appeared in another form later. The point is a willingness to seek useful work without waiting for a higher title. His career happened to reward that approach, while he does not claim every company will do so automatically.'
],3731.36,3867.92,speaker='Boris Cherny'))
b.append(qa('Why leave Meta for Anthropic?',[
'Using an early ChatGPT product while living in Japan made AI feel like a field he had to work on. He was fascinated by the technology and by speculative possibilities he had encountered through science fiction. Conversations at Anthropic gave him a strong sense of shared interests and people thinking deeply about the same questions.',
'He also wanted to help make the technology develop safely. He describes becoming more conscious of risk after seeing new models and Anthropic’s investment in safety and alignment, including delayed releases. His examples of possible misuse and existential risk are his assessment, not independently established capability claims in this book.',
'The decision combined fascination, a cultural fit, and a mission. His metaphor of models as an alien life form conveys his excitement; it should not be mistaken for a factual claim about consciousness or biology.'
],3867.92,4127.28,speaker='Boris Cherny'))
b.append(qa('What felt different about Anthropic’s engineering culture?', 'He values a startup’s shorter distance between decisions and consequences: useful changes can seem obvious enough that less effort goes into persuading multiple layers. Mission is also personally powerful. He had felt it in Facebook groups’ community work, felt less of it in Instagram, and felt it strongly again at Anthropic. He acknowledges that geography or his own experience could have influenced the difference. He is describing what motivates him, not a ranking of how meaningful every employee’s work is.',4127.28,4214.88,speaker='Boris Cherny'))
b.append(qa('Why did Claude Code catch on when other model-connected tools already existed?',[
'Cherny contrasts the then-dominant coding autocomplete and Q&A model with a tool intended to act more broadly. His manager pushed him to build for capabilities expected about six months later rather than only what the current model could already do.',
'The product was initially weak and he used it for a small portion of his own coding. Later model improvements made the existing tool much more useful, matching the horizon the team had aimed for. He reports high fractions of agent-written code within his team and some others, plus a substantial increase in per-engineer productivity while Anthropic expanded.',
'Those usage and productivity numbers are internal claims made in the interview. The caption does not clearly establish the productivity metric, so the book does not convert them into an exact causal benchmark. His product lesson is to stay close enough to the model’s trajectory to serve near-future capabilities while avoiding a plan too far ahead to test.'
],4214.88,4374.72,speaker='Boris Cherny'))
b.append(qa('How do you avoid accepting large amounts of poor or subtly flawed model-generated code?',[
'Use the same quality bar for human and model code. If a change is poor, the team should refuse it and ask for improvement rather than lower expectations because an agent wrote it. Cherny thinks users can also ask for changes that are too large before learning to direct the tool well.',
'He chooses the method according to the work. Throwaway prototypes can be generated loosely. For maintainable product work, he usually aligns on a plan, inspects the implementation, and iterates with the model. Some core-loop details still matter enough to him that he writes them by hand.',
'He is enthusiastic about progress without saying the models are already excellent at every task. He sees substantial room to improve and warns that judgments about capability move quickly. That combination of optimism and retained review standards is more useful than treating generated volume as evidence of correctness.'
],4375.68,4592.48,speaker='Boris Cherny'))
b.append({'type':'table','title':'Three coding approaches in Cherny’s workflow','headers':['Approach','Appropriate context in his account','Human role'],'rows':[['Loose generation','Disposable prototypes and experiments','Decide whether the result is useful enough to keep exploring'],['Pair with the model','Maintainable product work','Agree on a plan, inspect changes, and request improvements'],['Handwritten implementation','Details where he has strong, specific preferences','Control the implementation directly']],'evidence':ev(4429.68,4592.48)})
b.append(qa('What do you think of Claude Code being used beyond software engineering?', 'He discovered a neighboring data scientist using it for SQL and analysis, then saw multiple sessions supporting data work, pipelines, and coding. He also reports salespeople connecting it with Salesforce and other sources. Those uses were not the original product intent. The examples return to latent demand: observe what users do with an adaptable tool rather than define its limits solely from the name.',4592.48,4641.28,speaker='Boris Cherny'))
b.append(qa('How do you view competition with Codex, and what makes users stay?',[
'He does not give a feature comparison because he says he does not personally use the competing tools and is unsure. The stickiness part of the host’s question therefore does not receive a definitive mechanism.',
'His management principle is to avoid letting competitors replace user problems as the product roadmap. Copying a visible feature is easier than discovering a better solution, but he wants the team focused on its own work, researchers’ needs, and users’ problems. He interprets more competitors partly as evidence of an important market, rather than only as a distraction to fear.'
],4641.28,4741.28,speaker='Boris Cherny'))
b.append(qa('Has not having a computer-science degree held you back?', 'He studied economics and left to build startups. He has not felt the missing CS degree blocked his own path and recommends learning programming through practical work, then adding theory as it becomes useful. His reasoning is that concepts are easier to connect to an actual product than to exercises without context. This is his experience and preference, not evidence that a degree never matters for a particular employer or technical field.',4741.28,4780.96,speaker='Boris Cherny'))
b.append(qa('What productivity advice would you give now?', 'His answer has changed with coding agents: learn to automate toil and coordinate several agents rather than depend only on faster manual typing. He describes a teammate using many parallel sessions and a task board to implement a feature over a weekend in a container. This is an anecdote about her workflow, not a verified effort comparison or a blanket recommendation to remove safeguards. Earlier his advice would have centered more on ordinary scheduling and focus habits.',4781.92,4860.8,speaker='Boris Cherny'))
b.append(qa('Do agents change the need for long coding focus blocks?',[
'In his own work, somewhat. He still enjoys quiet coding time, including weekends, but can begin several tasks from a mobile or web interface in the morning and inspect them later at a computer. He sometimes merges after review, or brings a change locally to edit.',
'He sees this as making coding accessible in fragmented schedules, including for managers who have not recently written much code. He is describing a changing interaction pattern, not declaring concentration unnecessary for understanding or reviewing complex systems.'
],4862.16,4975.52,speaker='Boris Cherny'))
b.append(qa('What would you tell yourself at the start of your career?', 'Use and develop common sense. Organizational history and misaligned incentives can pull people away from what users and a business actually need. In startups as well as large companies, he would trust practical judgment, examine assumptions, and build toward the real market or user problem. The advice ties his generalist work, side projects, migrations, and product choices back to the same habit.',4977.28,5030.32,speaker='Boris Cherny'))
save('source-ce5d21a3243dbd18','Stay close to users, code, and the next useful capability','Boris Cherny traces growth through generalist product work, shared infrastructure, earned trust, corrective decisions, and building Claude Code for a changing model frontier.',b,'ai',['Opening montage (0:00–about 1:00) repeats later exchanges and is represented once.','Closing thanks and channel requests (1:23:51 onward) omitted.'],notes='All 8 full compact chunks read. Preserved the complete career sequence and later Claude Code questions, including the unanswered direct comparison/stickiness question. Adjacent clarifications are nested. Approximate staffing, productivity, and adoption figures remain reported estimates; the unclear productivity metric is not invented. Garbled names and incidental metadata are avoided. Product/tool descriptions are interview-time claims, with no outside updates.')
