from write_section import *
b=[]
b.append(qa('What most explains your rapid rise to senior staff at Uber?',[
'Attwell credits the combination of a growing engineering organization, strong people to learn from, and a culture he experienced as meritocratic. Growth supplied many problems, though he acknowledges that a company does not need growth to have useful work. He also regards caring about the team as essential to sustained success.',
'His intentional choice was unusually intense work. He believes learning compounds and that managers assign valuable work after seeing evidence of capability, so he created time to develop that evidence himself. Early in his career, he expected to have more discretionary time than later. His claimed relationship between effort and growth is his judgment, not a demonstrated universal formula.'
],89,214.88,speaker='Brian Attwell'))
b.append(qa('Was the extreme effort worth it when you look back?',[
'For him, yes. He recalls being told during an internship that he might die, then recovering after a medication problem was discovered. What he regretted in that moment was not having built the things he still wanted to build. That personal experience conflicts with the familiar maxim that nobody wishes for more work at the end of life.',
'He also compares a painful period of teamwork with a hard-won sports match: the effort was difficult, but the shared outcome could make it memorable and enjoyable. He admits he overdid it at times. This is an unusually strong personal preference, not a claim that everyone should make the same tradeoff.'
],214.88,304.56,speaker='Brian Attwell'))
b.append(qa('How do you notice that you are working too much?',[
'He watches for reduced patience and irritability rather than relying chiefly on an hours limit. After weeks without a day off, his partner may notice he is becoming grumpy. That signal matters especially in management, where patience affects other people.',
'His earlier warning system was much worse. He recalls collapsing on the way home from Uber with chest pain and being unable to move for about 15 minutes. He later consulted a doctor and reports being told that anxiety and excessive work were involved. He uses the story to acknowledge that he should have cut back sooner.',
'He compares sustained effort with athletic training that still needs recovery. The account is a personal recollection of a serious event; it does not establish a medical diagnosis or a safe workload for another person.'
],304.56,404.4,speaker='Brian Attwell'))
b.append(qa('What concrete work helped you grow as an engineer?',[
'On a team addressing mobile maintainability during Uber’s expansion, he and a colleague, Yi, were among the most junior engineers. They listened to experienced colleagues debate options and noticed that eliminating bad approaches was easier than choosing the best remaining one.',
'After ordinary project work, they prototyped competing approaches using representative failures from postmortems. In one example, Attwell tested alternatives including RxJava on Android while Yi explored iOS, and they reviewed one another’s work. Working examples changed the team’s choice from an initial preference to an approach the experiments supported.',
'Their early hit rate was poor: many searches stopped at the edge of their knowledge, and the company would not necessarily have funded that exploratory time. After months of practice, they became better at finding useful questions and were increasingly invited into major decisions rather than overhearing them. Their influence later spread across a much larger mobile organization.',
'Attwell reports working roughly 90–100 hours a week, including weekends, with physical discomfort and headaches. He calls that the route he used to achieve an unusually young senior-staff promotion and makes a strong claim about its necessity. The book preserves it as his view; the episode does not establish that such hours are the only path, or that they are sustainable or appropriate for everyone.'
],404.4,614,speaker='Brian Attwell'))
b.append(qa('How much of that trajectory was luck?',[
'He separates frequent actions from infrequent decisions. Doing many small things well repeatedly gives less room for chance than choosing a company once every few years. He chose Uber intentionally, but recognizes that the choice could have gone wrong.',
'He thinks his effort and mindset would probably have served him well inside that particular merit-oriented setting. Joining an organization that did not value the same contributions could have delayed growth. He explicitly rejects a fully deterministic mapping from personal effort to career outcome.'
],614,693.5,speaker='Brian Attwell'))
b.append(qa('What signals made Uber attractive, and how would you evaluate another company?',[
'He would examine the quality of engineers and the hiring process that brings them in. He favors difficult, job-relevant tasks requiring reasoning about conflicting requirements, rapid assimilation of new material, and tradeoffs, rather than only recalling practiced solutions.',
'His example is reading a complex postmortem and debating what it reveals about the team or architecture. He believes designing good interviews for many distinct roles requires substantial leadership effort and ongoing experimentation. Assertions about tests and intelligence reflect his hiring philosophy, not independent scientific validation in the episode.'
],693.5,807,speaker='Brian Attwell'))
b.append(qa('How would you test the reasoning ability you are looking for?',[
'Attwell prefers tasks that require keeping multiple ideas and constraints in mind while remaining relevant to the job. An applied programming problem with conflicting requirements or a postmortem whose details challenge one another can reveal more than practiced recall.',
'He is also considering formal intelligence screening, especially to reduce the time spent on unsuccessful PM interviews. He describes such tests as a screening aid rather than a complete ranking of already strong candidates. His statements about their trainability, predictive value, and AI’s limitations are attributed claims and are not established as research findings by this transcript.'
],807,989,followups=[fu('Does greater intelligence imply better job performance?', 'He believes it contributes, but says strong technology companies have already selected a comparatively capable pool, so it explains less variation within a team than across an unrestricted population. He still wants applied experience and relevant skill, and acknowledges that no interview process perfectly predicts later performance.',866,945)],speaker='Brian Attwell'))
b.append(qa('Why are product managers harder to interview than engineers?', 'He sees the role as less consistently defined, more varied across disciplines, and lacking the same established educational and interview traditions. His organization asked several CEOs what excellent PM work looks like, wrote its own definition, and designed a process around it because there was little it wanted to borrow unchanged. He again frames intelligence screening as a possible early filter, while leaving later interviews to distinguish good from exceptional applied performance.',989,1089,speaker='Brian Attwell'))
b.append(qa('Beyond being smart, how do you choose the best use of your time?',[
'Attwell agrees that other skills need conscious development, especially prioritization. He considers the value of an initiative over a fixed period, how much his involvement changes its chance of success, and the time it will require. He is trying to maximize incremental expected value per hour.',
'The company’s top priority may already be well staffed by the time a junior engineer hears about it. A less prominent but still valuable initiative may have a larger gap that the engineer can fill. Working on the most important project and making the largest personal contribution are therefore different questions.'
],1089,1198,followups=[fu('What does success “with and without you” add to ordinary benefit divided by cost?', 'It asks what your presence changes. Early in a career, look for important work that will otherwise remain unstaffed. Later, match distinctive skills with a real problem where they can improve the outcome. These estimates are fuzzy; he explicitly rejects pretending to have several significant figures of precision.',1198,1251)],speaker='Brian Attwell'))
b.append(qa('How can an engineer learn to estimate business value?', 'Ask why a metric or quarterly goal matters. A model-recall target might be intended to reduce churn, which in turn relates to revenue. Use one-on-ones to understand why leaders choose or cancel projects. If the company has an initiatives sheet with estimated value or a reason each project matters, study that column: it exposes other people’s reasoning and helps build intuition. He expects this to be learned, since most new engineers have little business background.',1251,1348,speaker='Brian Attwell'))
b.append(qa('Why did you eventually become a manager?',[
'He delayed the move despite several managers recommending it. At his later company, a strong group of engineers already treated him as a technical leader, so he enjoyed directing work without the full obligations of formal management. When his boss said the group needed either him or a newly hired manager, he accepted because he wanted to protect a team and technical vision he cared about.',
'He initially did the job poorly, hiding in coding instead of handling management fundamentals. A new teammate once asked after three months whether Attwell was actually his manager. He took that as evidence of neglect, improved those skills, and afterward saw the organization reporting to him grow rapidly. The story does not make technical leadership an automatic substitute for people management.'
],1348,1498,speaker='Brian Attwell'))
b.append(qa('Why did more organizations keep moving under you?',[
'He begins with a belief that even a strong team may have major room to improve. Rather than preserve every inherited practice, he invites people to question assumptions, including his own. Suspicions about a long-standing process are useful starting points for discovering waste.',
'An integrations team maintained about 1,200 connections intended to gather restaurant-industry information. Each had once seemed a good investment, but maintenance had accumulated without a fresh comparison of value. A colleague questioned how all of them could still be equally important. The team spent days estimating their value distribution, stopped supporting a low-value subset, reduced pages, and improved support for the important remainder.',
'He describes the overall product as improving even though it now supported fewer integrations. Reclaimed time also enabled new work. The example shows how subtraction can create capacity when the useful outcome is broader than the count of supported items.'
],1498,1671,speaker='Brian Attwell'))
b.append(qa('How do you handle the people conversations when scope moves between leaders?', 'Attwell says these conversations need empathy and honesty. A capable person may nevertheless not be delivering what a particular role now requires, or may need a smaller scope. Explain the needed work, identify the gap, and recognize what the person still does well or contributed previously. His description favors clear expectations over hiding the reason for an organizational change.',1671,1712,speaker='Brian Attwell'))
b.append(qa('How can incentives keep managers from clinging to scope?',[
'He regards an automatic link between promotion and organization size as a poor design because it encourages empire building. His company originally borrowed a ladder resembling Uber’s, then attempted to improve it. Travis Kalanick challenged the revision as still too focused on scope and insufficiently insightful.',
'Attwell and a colleague then invested months in understanding other systems’ weaknesses. His core concern is that scope captures one kind of complexity while rewarding position and political maneuvering more than useful ability.'
],1712,1839,speaker='Brian Attwell'))
b.append(qa('What changed in the redesigned leveling system?',[
'They began with roughly a thousand examples of people differentiating themselves through real work, grouped those into about 250 attributes, and used an analysis he calls principal-component analysis to arrive at twelve skill dimensions. He describes compensation as rising with demonstrated skill and impact along those dimensions rather than primarily with position.',
'The emphasis shifts from influencing teams as a status marker to having sound ideas, including successfully questioning foundational assumptions. Communication remains a separate competency with examples of good work. He wants people to improve capabilities that generally help the company even if they are also trying to earn advancement.'
],1839,2037,followups=[
fu('Where did the initial examples come from?', 'He spoke with engineers, read books, and reviewed years of quarterly calibration notes. He wanted examples he knew had actually occurred, so the upper levels would not become an imaginary standard that nobody could attain.',1924,1980),
fu('How do you assess good communication?', 'Give a verbal description and concrete examples, then compare a person’s actual artifact with them. This can support a more grounded conversation than relying only on social proof, although it does not remove judgment.',2014,2053),
fu('Can a manager still bias the examples or exaggerate performance?', 'Yes. The framework changes what people posture about rather than abolishing politics. He thinks striving to look good at truth-seeking or communication is still more useful than merely collecting scope. Leadership must also spot-check calibration and act on deliberate misrepresentation; he presents this as substantial continuing work, not a solved measurement problem.',2053,2139)
],speaker='Brian Attwell'))
b.append(qa('Is it especially difficult to remove an underperformer whom everyone likes?', 'Attwell disagrees with treating this as an insurmountable problem. A frontline manager may feel attached and see the social bonds, but hardworking colleagues may also resent covering for the person. He expects a difficult immediate response can give way to a happier team afterward. This is his view of the tradeoff; the episode does not show a particular termination or prove that this outcome always follows.',2139,2185,speaker='Brian Attwell'))
b.append(qa('How do you provide evidence of truth-seeking?',[
'Look for useful discoveries that challenge accepted practice: an important problem in plain sight that nobody recognized, or a justified departure from an industry norm because the team’s constraints differ. A novel opinion by itself is not enough; there needs to be value and reasoning behind the divergence.',
'He admits subjectivity remains and managers must be calibrated on examples. Existing technology-company ladders are not wholly broken, and he expects changes at the margin rather than completely different results. The distinction he wants is somewhat more attention to the leading behaviors that produce good results, rather than rewarding only an already-achieved position or outcome.'
],2185,2332,speaker='Brian Attwell'))
b.append(qa('Could excellent work still be rewarded when its project gets deprioritized?', 'Yes, in his system. If a person did excellent work and leadership cancels the project for a reason unrelated to that work, the person’s contribution can still be evaluated. He places responsibility for late cancellation partly on leaders. At the highest levels, he expects greater business judgment about whether a project should exist, so that qualification changes how the case is assessed.',2332,2363,speaker='Brian Attwell'))
b.append(qa('Why do some large companies fail to reward their highest performers strongly?', 'Attwell thinks they can sometimes retain people anyway, especially when appreciating equity already makes compensation feel good. He objects to using past investment gains as a reason to reduce future reward and says his company tried to avoid that. He favors designing processes around fairness for long-term organizational benefit. These are his judgments about incentives, not a verified description of every large company’s pay policy.',2363,2427,speaker='Brian Attwell'))
b.append(qa('What did starting at Google teach you?',[
'It left him skeptical of how well large technology companies are managed. He recalls a teammate he thought did little work, yet a manager and director emphasized that the person was pleasant and liked. Attwell complained, and the person eventually moved elsewhere, though he cannot prove his complaints caused the move.',
'He thinks leadership should at least have had a serious performance conversation. The anecdote is his perspective on one situation, not an evaluation that the reader can independently verify.'
],2427,2522,speaker='Brian Attwell'))
b.append(qa('Why might a large company avoid that hard conversation?',[
'Attwell argues that individual-team performance can be weakly connected to a large company’s near-term results, letting managers prioritize convenience over difficult improvement. Raising standards takes energy; asking less of people often creates little resistance. He expects standards to drift downward unless leaders deliberately counter the trend or a crisis forces change.',
'He also reports that several Google managers told him of a past strategy to retain smart people even when they were not productive, partly to keep them from competitors. He explicitly says he did not see this in writing and cannot prove it existed. That uncertainty is central; the anecdote should not become an established corporate policy.'
],2522,2633,followups=[fu('Do you see merit in retaining talent mainly to keep it from competitors?', 'No. He doubts a company can monopolize intelligence because there are many capable people. His answer concerns the strategy as he understands it, even though the alleged policy remains unverified.',2600,2633)],speaker='Brian Attwell'))
b.append(qa('What is the thesis behind the company you are working on now?',[
'Attwell describes a goal of making fresh prepared food inexpensive enough that people can choose to reclaim the time spent cooking. He sees large avoidable costs in food labor, logistics, property, and ordering systems, and believes a sufficiently integrated approach can reduce them.',
'He reports restaurant robotics reducing labor cost, a lunch-logistics network lowering meal cost, lower-cost real estate, and the Otter software platform improving orders. The percentage reductions, order share, and trillion-dollar opportunity are company claims he makes in the interview, not independently verified market facts.',
'Some products are early while others have many customers. His prediction that robotics will eventually do much more of this work expresses the company’s ambition. The useful mechanism is coordinating several cost reductions across a supply chain rather than assuming one app alone makes prepared food affordable.'
],2633,2796,speaker='Brian Attwell'))
b.append(qa('Why does the company keep such a low public profile?',[
'He says conventional publicity can help fundraising, hiring, and a founder’s reputation. In their case, Kalanick already had wealth, funding access, and a strong network, so those benefits were smaller. Attwell sees costs in leadership distraction, negative coverage, and alerting competitors to the company’s plans.',
'He recounts public launches attracting many competitors and favors quiet execution at the parent-company level. This is a strategy suited to their circumstances, not a universal case against distribution or brand building.'
],2796,2961,followups=[fu('How do you distribute products while remaining quiet?', 'Much of the business is B2B, and individual products such as Picnic and Otter still have names, advertising, and sales activity. The company speaks less about its central organization, rather than never promoting products. Recruiting is harder, which is part of why he is willing to appear on the podcast.',2961,3018)],speaker='Brian Attwell'))
b.append(qa('What is your biggest career regret?',[
'He distinguishes mistakes he lacked the knowledge to avoid from choices where he knew better and stayed silent. As a young Apple intern, he had a chance to show Steve Jobs a prototype improving phone usability in sunlight. While his mentor pitched its product potential, Attwell minimized it as a small amount of code. Jobs left, and the mentor explained that the team had lost a chance to win support.',
'Attwell does not dwell on that as a regret because an inexperienced teenager did not know how to pitch product value. He treated it as something to learn. The cases he regrets involve recognizing midway that a decision was wrong but failing to tell people because the conversation was uncomfortable.',
'He cannot share a concrete private example without affecting others, so he offers a hypothetical instead: tell the team that your earlier judgment was wrong and give them the chance to reconsider. Even if they do not change direction, colleagues deserve the information. He thinks you owe them the benefit of believing they might listen.'
],3018,3260,speaker='Brian Attwell'))
b.append(qa('What is it like working directly with Travis Kalanick?', 'Beyond the familiar intensity, Attwell sees a patient teaching side. At a senior-engineering offsite, Kalanick taught backgammon and coached people in water skiing between work sessions. Attwell describes enjoying that patience, including with less athletic teammates. This personal story adds a different dimension without claiming it represents everyone’s experience of the founder.',3260,3310,speaker='Brian Attwell'))
b.append(qa('Should someone choose an early-stage company largely because of its founder?', 'He thinks that can make sense because a founder with substantial control shapes composition, culture, and standards. A strong person can multiply the company’s effectiveness, while the wrong leader can do the opposite. The advice is to assess that influence carefully rather than treat founder reputation alone as a guarantee.',3310,3359,speaker='Brian Attwell'))
b.append(qa('What advice had the greatest impact on your career?', 'A high-school computing teacher repeatedly told him to figure things out himself. Attwell never knew whether that was deliberate teaching or simply the teacher not knowing the answer, but it helped him accept self-directed learning. He believes most professional learning requires that habit: keep moving beyond the area in which you are already comfortable.',3359,3411,speaker='Brian Attwell'))
b.append(qa('Which books would you recommend?', 'He does not identify one transformative title. Instead he suggests studying interview-preparation material for an adjacent discipline: system design for a front-end engineer, or product-management material for a back-end or machine-learning engineer. Such books provide broad introductory vocabulary and exercises that can make ideas stick, improve conversations with other roles, and establish a foundation for deeper learning. He is recommending a use of the genre, not claiming interview tricks create expertise.',3411,3489,speaker='Brian Attwell'))
b.append(qa('What would you tell yourself when first entering the industry?', 'Be more courageous and less embarrassed about failure. He immediately qualifies that as an opening for a larger discussion of understanding emotions, possibly including therapy, rather than a command that makes embarrassment vanish. He thinks greater emotional awareness can help both the person and their relationships.',3489,3522.04,followups=[fu('Is that easier said than done?', 'Yes. He agrees that embarrassment is felt and that the short advice needs a deeper conversation about one’s feelings and how to understand them.',3500,3522.04)],speaker='Brian Attwell'))
save('source-03046274935dc220','Seek better answers, then design incentives around them','Brian Attwell connects intensive early learning with prioritization, truth-seeking, management responsibility, and a critique of ladders that reward scope alone.',b,'leadership',['Opening montage (0:00–about 1:30) repeats later exchanges and is represented once.','Closing thanks and channel requests (58:44 onward) omitted.'],notes='Read all 5 complete chunks. Thirty initiating rounds preserved, with related clarifications in order. Strong claims about effort, intelligence screening, AI, Google policy, and company scale are attributed and qualified. Alleged Google policy is explicitly unverified; serious health anecdotes remain personal accounts. The regret example is marked as hypothetical rather than invented as a specific event.')
