from write_section import *
b=[]
b.append(qa('What did your career look like before Amazon?',[
'Evans wanted to work in computing as home computers emerged. Apple’s reply to a letter about employment helped shape his choice of university; he attended Carnegie Mellon and later completed a master’s degree at Purdue. His early jobs were a sequence of small companies connected loosely by networking, search, network management, advertising, and audio streaming, with a brief detour into entertainment lighting.',
'Amazon eventually recruited him partly because streaming-audio experience fit its planned video work. Most of the startups after his first struggled or failed around the dot-com era. He describes being made redundant twice, with his confrontational behavior contributing. Becoming an Amazon VP was not his initial life plan; the path evolved.'
],60,213.76,speaker='Ethan Evans'))
b.append(qa('Why did you initially choose startups over established companies?', 'The first choice was driven mainly by friends and an apparently attractive opportunity, not a carefully reasoned comparison of company sizes. Friends joined a local company founded by professors and introduced him to stock options. An earlier-joining roommate did especially well; Evans joined later but earned enough for a house down payment. Only afterward did he learn to make more intentional career decisions. The story illustrates why a successful early choice need not have begun as a sophisticated strategy.',215.2,301.52,speaker='Ethan Evans'))
b.append(qa('Did you see the layoffs coming, and what part did abrasiveness play?',[
'No, despite warnings. His first manager had already noticed combative problem-solving, and Evans once proudly framed being a “loose cannon” as being aimed at people who were wrong. Technical ability and energetic execution still carried him into startup leadership, but peer conflict became increasingly costly.',
'In one company, a product leader warned that the planned scope could not be delivered with available time and resources. Evans now thinks the warning was correct; at the time he treated it as disloyalty to the mission. During downsizing, he offered to leave for another startup, and the CEO accepted. He suspects removing conflict made that easier.',
'In the next company, he argued with a sales leader who promised capabilities that did not exist. Evans still sees the truthfulness problem, but recognizes that the company was fighting for survival. He was the only person in the resulting “layoff,” so he regards it as being fired to remove contention. After the second experience, he finally investigated his own recurring role in the pattern and changed how he dealt with disagreement: more questions and listening, less escalation.'
],302.88,532.16,speaker='Ethan Evans'))
b.append(qa('Was early aggression useful, or would interpersonal skill have made it better?', 'Evans thinks energy combined with good interpersonal skill would have been better. He still favors having an opinion and advocating for it; pure compliance is not his model of leadership. The difference is how one argues. His earlier version raised his voice and dismissed ideas as stupid. A more skillful version can be persistently challenging without being abrasive or hostile. Being right often let him get away with the poor version, but did not make it the best version.',533.84,618,speaker='Ethan Evans'))
b.append(qa('How can a leader avoid being removed through politics behind their back?',[
'He says excessive confrontation can cause people to stop debating with you and start discussing you with others. The first defense is to leave enough room for honest disagreement that people do not feel a private campaign is the only route.',
'The second is a wider set of trusted relationships. Evans lacked allies who would tell him when another peer raised a concern; instead those people agreed that he was a problem. Technical correctness cannot replace relationships and the feeling people have while working together. He acknowledges that organizations sometimes choose a less technically good solution because it feels easier to support.'
],618,735.68,speaker='Ethan Evans'))
b.append(qa('What finally made you take interpersonal skill seriously?', 'The second departure, followed by difficulty finding another job after the dot-com crash and September 11, forced reflection. An interviewer challenged the story that he had been so valuable yet could not be retained. Evans concluded the missing capability was not coding or driving projects, but working well with people. He studied motivation, questions, and the psychology of work, then became interested in how to lead and inspire rather than only state answers. The painful feedback became a sustained learning interest.',737.28,850.88,speaker='Ethan Evans'))
b.append(qa('Why was moving across the country to Amazon worth the risk?',[
'While at a search company partnered with Barnes & Noble, Evans had investigated why that retailer was losing online to Amazon. Seeing Amazon through a competitor gave him a concrete appreciation of its capabilities, which he could discuss when Amazon’s recruiter approached him.',
'He was also tired of startups struggling with funding and product-market fit. Amazon was public and not yet profitable, but its scale looked stable compared with firms of dozens or hundreds of people. The decision combined admiration for the business with a desire for a different risk profile; it was not a bet on the million-person company Amazon later became.'
],850.88,960.24,speaker='Ethan Evans'))
b.append(qa('What did promotions to director and then VP actually require?',[
'For director, Evans describes the ability to lead a business or major effort with only high-level goals. In his case an outsized event mattered: he pursued a video partnership with TiVo despite leadership’s advice against it, explicitly giving the senior leader a chance to order him not to proceed. It worked, and his promotion narrative emphasized that the partnership would not have happened without him.',
'He also made his career priority clear to his VP, who was preparing to leave. Evans politely explained that if Amazon did not value his growth as much as he did, he would need to consider that. The timing created retention pressure because both leaders leaving would damage the project. He sees both demonstrated judgment and explicit advocacy as central.',
'He admits a troubling managerial tradeoff: when two people were similarly qualified, the one pushing for advancement and threatening to leave sometimes got priority over the patient team player. He describes practical retention pressure rather than defending it as ideal fairness.',
'The successful project was a genuine risk. An ordinary result might have left him where he was, while a disaster after ignoring advice could have hurt him. He would take more calculated risk in retrospect, but his outcome does not erase the possible downside.',
'VP involved a longer process of building stakeholder support and trust with a stable manager. He worked on a partnership in which he would solve important problems and his manager would advocate for recognition. After roughly two and a half years, the VP agreed to stake his reputation on the attempt, without guaranteeing the final decision. A reorganization soon afterward highlights how favorable timing mattered alongside effort.'
],962.24,1574.64,speaker='Ethan Evans'))
b.append(qa('What went wrong when you promised a strong engineer a promotion early at Amazon?',[
'A young engineer agreed to help ship the first version of the product in return for support moving from the entry engineering level to the next one. Evans agreed in good faith but assumed promotion worked as it had in startups. He was preoccupied with launch problems and did not know Amazon had fixed review cycles. The window passed.',
'He explicitly owns the error. The engineer was not responsible for the manager’s ignorance, yet the engineer bore the career cost. Evans recommends that employees learn the process anyway: check whether the manager knows it, identify deadlines, and ask about concrete documents and dates. A new manager may sincerely intend to help while lacking the necessary procedural knowledge.',
'The engineer left and had a successful career elsewhere. Evans regrets the lost time but stresses that a year’s setback need not define a career lasting decades. The appropriate lesson is both managerial accountability and employee awareness of the process, rather than blaming the employee for a broken promise.'
],1574.64,1753.36,speaker='Ethan Evans'))
b.append(qa('Why leave an 800-person organization for the Twitch integration role?',[
'Amazon used a VP as an integration liaison after acquisitions, while leaving the acquired company’s CEO in charge. Evans sought that position after Amazon bought Twitch because it would test influence without authority. He would advise the CEO rather than command him, with no team of his own.',
'He had learned to run a large global organization with formal authority. Now he had to work with a younger, newly wealthy founder serving an audience and business culture different from his own. He gave up the large team to learn that challenge and enjoyed both the partnership and learning to stream on Twitch.'
],1754.24,1875.68,speaker='Ethan Evans'))
b.append(qa('What gaps did you see in a young founder running a rapidly scaling company?',[
'Evans recalls Twitch treating continuing losses as normal because venture funding had always been available, and initially assuming Amazon’s money made profitability less urgent. His leadership wanted profitability, so a core challenge was establishing that the objective mattered at all.',
'He also saw the difficulty of loyalty to early employees whose skills did not scale with the organization. Bringing in a more experienced leader above a friend, or changing their role, required hard conversations and sometimes led to angry departures. He notes that the founder might describe the gaps differently; this is Evans’s view of the learning process.'
],1877.12,2025.6,speaker='Ethan Evans'))
b.append(qa('How did Jeff Bezos and Andy Jassy differ as leaders in your experience?',[
'Evans reports dozens of meetings with each and emphasizes founder status as a major difference. He recalls a budget discussion in which Bezos answered a warning about limited cash by asking how much there was, because he might want to spend it. Evans interprets that as the founder claiming the authority to take extraordinary bets with the company he created.',
'He describes Jassy as a more conventional executive who must partner with other leaders and operate within board and founder expectations. Both demanded a great deal.',
'His personal fit differed too. He felt Bezos’s questioning was followed by enthusiasm and a sense of shared commitment, while Jassy’s questioning felt more like scrutiny followed by personal accountability. Evans explicitly says other executives could have experienced the opposite. This is a comparison of his working relationships, not a universal ranking of either person.'
],2027.68,2209.6,speaker='Ethan Evans'))
b.append(qa('What happens to a VP’s review when a business initiative fails?',[
'Evans distinguishes meeting near-term goals from achieving the business vision. Prime Gaming could ship features and meet some financial targets without making Amazon the major gaming force its founder imagined. He says he received strong VP ratings even while some businesses did not deliver that larger ambition.',
'He recalls expecting to hit all his Appstore goals while considering them ultimately unimportant. His broader criticism is that large organizations can let products persist because nobody wants to admit failure or close them, while nobody knows how to make them major successes. His comments about later shutdowns and possible future gaming outcomes are interview-time claims and speculation.'
],2213.36,2362.08,followups=[fu('Why not change the goals to match the vision?', 'Because the goals that determine pay and review create a different incentive from the goals the company ideally needs. Competing with a preinstalled app store from a sideloaded position was important but not something Evans knew how to achieve, so he resisted being measured on it. He candidly admits wanting achievable evaluation goals while the business needed a much harder outcome. An ambitious vision is not automatically a workable plan.',2364.16,2481.12)],speaker='Ethan Evans'))
b.append({'type':'table','title':'Three different measures of success','headers':['Measure','What it asks','Risk Evans identifies'],'rows':[['Project delivery','Did the team ship the agreed work?','Visible activity can look like success'],['Performance review','Did the leader meet negotiated goals?','Goals may favor what is achievable'],['Business vision','Did the initiative create the strategic result?','The organization may keep meeting goals without progressing toward it']],'evidence':ev(2213.36,2481.12)})
b.append(qa('What do stack ranking and performance plans get right and wrong?',[
'Evans describes a historical Amazon attrition goal that pushed managers to deal with weak performance. When it was removed experimentally, he says managers avoided hard conversations, particularly with well-liked people, so the goal returned. He gives varying annual proportions as recollections of the system, not current verified policy.',
'The problem is that a quota can turn a support process into a departure process. By the time a manager writes a PIP, they may already have decided the employee should leave. Confirmation bias and pressure from HR or leadership to record an exit can work against genuine recovery. Taking one employee off the list may create pressure to identify another.',
'He reports that the people who asked him for help on Amazon PIPs were later fired, as were several who did not use his coaching. He now urges people to prepare for another role. His strong warning comes from personal cases rather than a controlled success-rate study.',
'His diagnosis is that companies often do not train managers to address issues early or conduct useful difficult conversations. A formal plan arrives late and under distorted incentives, even when the manager initially believes they intend to help.'
],2481.12,2769.92,speaker='Ethan Evans'))
b.append(qa('What prevents a manager from framing a report unfairly?',[
'Evans distinguishes a pattern of removing many employees, which can become visible through turnover, from one targeted case, which may be hard to challenge. The manager has status and can establish the performance narrative before the employee complains.',
'The same review count can support opposite narratives: a strong engineer improving everyone’s work or a person nitpicking while producing little original code. Neither count alone answers the value question. The manager may be malicious or may honestly evaluate the work differently.',
'He says he has not personally targeted an employee this way, and recognizes that good managers benefit from capable partners. The danger concerns a vindictive leader with power over the narrative. His practical advice is to improve the relationship if possible or find another manager, rather than assume HR will automatically rescue the employee. This is an account of a vulnerability, not an endorsement of unfair treatment.'
],2772.24,3043.36,speaker='Ethan Evans'))
b.append(qa('What advice would you give yourself at the start of your career?',[
'Keep preferring growth. He compares his career ladder to an escalator because fast-growing businesses created upward movement alongside his own effort. The scale change he reports at Amazon supplied opportunities that personal drive alone could not create.',
'Learn sooner that work is done with humans. Expertise and being right should be paired with friendships, trust, and being known. An introvert can use writing and online tools rather than force a single extroverted style. Amazon approached him, and he sees a strong reputation as part of what makes that kind of opportunity possible.'
],3044.96,3143.12,speaker='Ethan Evans'))
save('source-11a9088fd11380a0','Pair ambition with relationships and procedural knowledge','Ethan Evans traces a rise from abrasive startup leader to Amazon VP while exposing the gap between output, recognition, business value, and managerial power.',b,'leadership',['Opening trailer (0:00–about 1:00) repeats later exchanges and is represented once.','Closing course, website, and channel requests (52:24 onward) omitted.'],notes='All 5 complete compact chunks read. Preserved 16 initiating question rounds and the explicit goal-setting follow-up. The extended director/VP answer remains with its initiating promotion question. Personal recollections and current-sounding business or HR claims are attributed to Evans; no external facts are supplied.')
