from write_section import *
sid='source-82b7300b1b1abb68'
b=[]
b.append(qa('What work and team context supported your unusually fast growth?',[
'Simon stayed with the same team and manager for about five and a half years. That continuity was unusual in his experience of Meta, but the team’s responsibilities changed substantially. It worked in ads payments, initially improving payment experiences and revenue, then supporting a large infrastructure migration, and later returning to product work.',
'The product context mattered. Revenue provided a relatively direct measure of impact, while local behavior created concrete problems to solve: in Thailand, for example, people bought through Messenger and exchanged bank slips as payment evidence. His career story therefore combines organizational continuity with changing technical and product scope, rather than repeating the same job for years.'
],55,152,speaker='Simon'))
b.append(qa('How did you earn the IC3-to-IC4 promotion in your first half?',[
'His earlier Meta internship reduced the learning curve for custom internal tools. He estimates that familiarity with tools such as Phabricator and the task system saved four to eight weeks. Before joining full time, he had also explored technologies through small projects, so bootcamp tasks were easier and he could help other new hires.',
'He joined as the second engineer on a new ads payments team. That gave him substantial access to a technical manager and impactful projects. Simon says the projects he delivered produced more than three times the team’s half-year revenue goal. The behavioral distinction was ownership of complete projects: finish the task, seek the next related opportunity, investigate disappointing results, and bring the work to a conclusion while asking for help where needed. In his account, promotion followed demonstrated next-level behavior rather than promising potential.'
],153,449,followups=[
fu('What preparation was actually useful before joining?', 'Small React projects and familiarity with what different technologies did were more useful than trying to memorize unavailable internal documentation. He describes engineers as pattern matchers: experience with TypeScript, for example, makes Meta’s Flow easier to learn even though the two are not identical. Exploration gave him enough vocabulary and examples to recognize new tools quickly.',250,332),
fu('Did an internship on another team still help?', 'Yes. The team was different, but internal tools and the workflow for landing code transferred. His internship did not remove the need to learn the product domain; it removed friction in getting started.',332,351)
],speaker='Simon'))
b.append(qa('Why join a tiny product team, and where did the technical mentorship come from?',[
'He originally expected to join an infrastructure team because C++ infrastructure was his interest and his internship background. During bootcamp, however, the first manager he met connected career growth with revenue impact and made a persuasive case for ads payments. The team also felt welcoming.',
'The manager had recently moved from IC6 engineering to management and could guide technical decisions as well as product experiments. Simon ran 20 experiments in his first half when the broader organization ran about 50. He attributes much of that velocity to direct, technically informed coaching.'
],449,563,followups=[fu('Why were you already focused on impact as a new graduate?', 'He had set a personal goal of reaching IC5 within three years and explicitly asked prospective managers how they could support it. His eventual manager drew a possible path on a whiteboard and had followed a similarly rapid path himself. Simon credits that manager heavily; the opportunity was not simply the result of individual effort in isolation.',563,632)],speaker='Simon'))
b.append(qa('What produced the first “redefines expectations” rating at IC4?',[
'Simon says impact was the primary driver. His project exceeded an already ambitious team revenue target measured in many tens of millions of dollars. Recruiting and onboarding additional engineers also contributed, and he broadened his reviews across JavaScript, Hack, Android, and iOS as the team grew.',
'The revenue result was not obvious at the outset. A strong data scientist suspected opportunities, but several initial experiments were neutral. In one, a failed-payment notice did not help advertisers as expected; examining the result led to better targeting and design, after which the project contributed roughly a fifth of his impact that half. In another, a daily script changed advertiser settings but experimentation logging failed. He read the code, contacted the experimentation team, and worked with the data scientist to understand the failure. The important pattern was continuing to investigate rather than declaring the first neutral result final.',
'His code review also aimed to develop people. That required calibration: some feedback said his reviews were overbearing, while other feedback said they made colleagues better engineers. He does not present helpful review as having been effortless or perfectly balanced from the start.'
],632,1068,speaker='Simon'))
b.append(qa('Did you expect those early ratings, and how did you interpret them?',[
'He had little context for the rating scale. As a new arrival from Sweden, he had not understood that restricted stock would become a large part of compensation, and he was not predicting ratings closely. The first promotion was revealed through his manager’s routine of taking newly promoted reports to dinner.',
'He was happy with the later top rating, but receiving strong results so early made it hard to judge how unusual they were. His only prior comparison was a promotion with a “greatly exceeds” rating. He knew someone else with a top rating, which also made it seem less rare. His account cautions against treating a person’s early expectations as a reliable guide to the broader distribution.'
],1068,1199,speaker='Simon'))
b.append(qa('How could the highest performance rating come without a promotion?',[
'In Simon’s explanation, ratings largely recognized what he achieved, whereas promotion asked how he achieved it. IC4 work meant driving his own project. IC5 required broader responsibility for others and their projects. He was helping onboard people but was not yet accountable for their success, so very large individual project impact did not by itself demonstrate the IC5 role.',
'He and the host stress that ratings and promotion are correlated without mapping one to one. Repeating a great deal of current-level work can produce a strong rating while leaving the next-level behavioral gap unresolved.'
],1199,1295,followups=[fu('Did you ask your manager about the missing promotion?', 'He remembers being sufficiently happy with the rating that he did not press the question. This was not an account of a promised promotion being denied.',1250,1273)],speaker='Simon'))
b.append(qa('What happened during the COVID review pause and your eventual IC5 promotion?',[
'The first COVID half used annotations rather than normal ratings and did not include promotions. Simon understood his annotation as indicating substantially above-expectation performance. He was disappointed because he felt on track; at that point a single half represented a large fraction of his career, although he now recognizes careers are much longer.',
'In the next half, he received another “redefines expectations” rating and the IC4-to-IC5 promotion. He qualifies that result: ratings were somewhat boosted to recognize work from the prior half, and his unadjusted result might have been near the boundary with “greatly exceeds.” He does not claim that all strong performers were automatically bumped to the top rating.',
'The substantive change was leading a pod of about four people through an unscoped product space from initial idea to completed projects. The product itself was not as successful as hoped, but handling the work, people, and director-level escalations showed broader ownership and communication. Promotion therefore reflected changed responsibilities even when the product outcome was imperfect.'
],1295,1513,speaker='Simon'))
b.append(qa('Why did the team trust you to lead a pod while you were still IC4?',[
'Simon sees two foundations: strong technical ability and an interest in people’s growth. He had studied computing from high school in Sweden and enjoyed solving difficult problems across platforms. He also cared about whether colleagues succeeded, had helped people improve, and had already done some sprint planning before taking full responsibility for a pod.',
'He distinguished prioritizing work from owning its outcome. Earlier he could help plan tasks without being responsible for the project’s or engineers’ success; the pod leadership assignment added that responsibility.'
],1513,1609,followups=[
fu('Did that leadership include career conversations?', 'With some people, yes. With others, he focused on whether they were happy and growing in a weak area rather than on a formal promotion plan. He remembers mentoring roughly four engineers around IC3 and IC4 while also managing one intern and serving as a peer for several others.',1609,1679),
fu('How did you help a struggling intern obtain a return offer?', ['The intern needed more time with fundamental React or Hack concepts and internal data modeling than anticipated. Simon invested enough time to get her over that early hump, after which progress improved. Helping her secure a return offer remains one of his proudest moments.', 'He calls generosity with time a potential way to create future capacity, because better-supported colleagues can contribute more independently. He also admits that some investments do not move the needle, that he may persist too long, and that helping this intern intruded on time with his wife. The story supports attentive coaching, not unlimited self-sacrifice as a universal rule.'],1679,1793)
],speaker='Simon'))
b.append(qa('What changed between IC5 and IC6?',[
'He earned the next promotion in two halves. First, one pod became two pods with roughly seven people, forcing him to delegate sprint planning and recruitment follow-through. He coached new pod leads and colleagues doing outreach, sometimes retaining the difficult initial recruiting conversation while letting others manage the candidate afterward. Those assignments also created growth opportunities for the people receiving them.',
'His initial delegation had a serious gap: he trusted that work would succeed without tracking it well enough, then discovered slippage near the end of the half. He later learned to zoom out, establish milestones and goals, notice stalled projects or struggling people earlier, and intervene in the specific gap rather than wait for a crisis.',
'His later scope included an eight-person team plus a separate project involving about 13 people. This tested whether he could combine roadmap and people leadership with deep technical contribution. Detailed reviews across clients and back ends helped him understand system interactions and catch incompatible implementations. Near a payment milestone, he also debugged a difficult path spanning Android or iOS, Instagram servers, Meta’s main backend, C++ payments infrastructure, and an external payments partner. He credits both broad coordination and the ability to go deeply into a hard technical problem.'
],1793,2313,followups=[fu('What specifically fixed the accountability gap after delegation?', ['His manager’s principle was that delegation did not remove responsibility for the outcome. Simon began using regular progress conversations and two views of work: a project breakdown and a people breakdown. A project may look healthy because one person is compensating for another who has stopped progressing; the people view reveals a need for support.', 'He also had to avoid the opposite error. Earlier colleagues asked him to step back because he was interfering with their opportunities to implement and grow. His eventual approach was to trust colleagues with execution while checking progress and supporting them through the responsible lead, rather than personally controlling every detail.'],2290,2477)],speaker='Simon'))
b.append({'type':'table','title':'What changed in Simon’s ownership','headers':['Stage','Primary responsibility','Gap or new practice'],'rows':[['IC3 to IC4','Bring an assigned project to a useful conclusion','Investigate results, find the next opportunity, ask for help'],['IC4 to IC5','Own a pod’s projects and help its people succeed','Plan an initially unclear space and communicate escalations'],['IC5 to IC6','Deliver through several leads and teams','Delegate, track people and projects, and intervene selectively']],'evidence':ev(396,2477)})
b.append(qa('After reaching IC6, how did you decide whether to pursue management?',[
'He remained ambitious, but management presented an identity concern: he valued being a capable engineer and worried that years away from technical work could leave him feeling less useful. The opportunity nevertheless came with his longtime manager’s support. Both had moved to London, and his manager was leading two teams with too many direct reports. Simon already led one of those teams technically.',
'He chose to try management because learning under a manager he admired seemed unusually favorable. He hoped to become a similar kind of manager, rather than viewing the move as the inevitable next promotion.'
],2477,2632,speaker='Simon'))
b.append(qa('What made that manager unusually helpful?',[
'Simon emphasizes care for people, projects, and impact; familiarity with Meta’s processes; and firsthand understanding of rapid engineering growth. The manager was also strong at product direction, setting a clear roadmap and communicating upward and downward. That let engineers execute while learning how to reason about data, growth, and product choices.',
'Written communication was another major lesson. Simon believes people can do excellent work yet limit their careers by explaining only what they did, without explaining why it mattered, what was learned, or what the company gained. A clear internal post can reach thousands and remain available for future decisions.'
],2632,2798,speaker='Simon'))
b.append(qa('What makes a project update effective?',[
'Assume a reader may spend only five or ten seconds on it. Simon recommends a genuinely short summary, visible before any “see more” expansion, with meaningful numbers when available. Readers should be able to recognize the result and its importance immediately.',
'He organizes the early portion around context, impact, and next steps, then offers technical details for specialists. Most of a large audience will not know the exact subsystem, but they can still care about outcomes and reasons. The host adds that engineers often lead with code-level investigation that only one or two collaborators understand; status, metric movement, and why the audience should care are more useful first.'
],2798,2964,speaker='Simon'))
b.append(qa('What did the management experiment teach you about technical work and role fit?',[
'He managed for less than a year, too little time to know whether his technical abilities would truly decay. The more immediate problem was that he struggled to stop doing technical work. Reports asked him to step away; when he saw a gap, his old tech-lead instincts made him want to fill it. He acknowledges that he did not fully correct this before returning to individual contribution.',
'The circumstances were also unusually difficult. His immediate manager had an accident and was out for months, his skip-level manager was on parental leave, and the nearest available leader was a California-based director returning from prolonged sick leave. Simon was in London, so context and time-zone support were weak. He also had to leave London and was trying to support two engineers who wanted IC5-to-IC6 promotions on a small team. He believes he overpromised: one could take his former technical leadership role, but finding equivalent scope for both was hard.',
'Burnout and the loss of his support network contributed to switching back. When a director asked if he wanted to return to IC work, the answer felt immediately right. He remains open to management later. His conclusion is qualified: better circumstances might have kept him in management longer, although he suspects he might still have returned to engineering.'
],2964,3257,followups=[fu('Why did returning to IC work fit better?', 'At IC6 he can combine hands-on work with mentoring and coaching while having more choice about whom and what to help. In management, developing and supporting every report becomes a central obligation and evaluation criterion. As an IC, those activities can add value without becoming his entire job. He is pleased with that flexibility, while recognizing that IC leadership still carries responsibilities.',3193,3285)],speaker='Simon'))
b.append(qa('What was the discretionary or additional equity you received?',[
'Simon describes additional equity as extra restricted stock units granted at a director’s discretion. He received it twice: around the IC5-to-IC6 promotion and about a year later as he moved into management. The first arrived through an unexpected 15-minute director meeting. He had seen compensation-group posts about such grants but recognizes that those posts skew toward unusually strong outcomes.',
'He speculates that retention and a low original new-graduate stock grant may have contributed to the first award; he does not know the decision makers’ full reasoning. He associates the second with successfully shipping a priority product in London faster than expected. Together, the awards materially increased his compensation. Market comparisons were hard at the time because Meta’s stock price had fallen.'
],3285,3528,followups=[fu('What did you think when a director scheduled a meeting without an agenda?', 'He had no clear expectation and was nervous. The unexpected meeting turned out to announce good news. This is a personal anecdote, not a dependable signal for interpreting every short leadership meeting.',3478,3529)],speaker='Simon'))
b.append(qa('From your experience as intern, intern manager, and intern director, what helps interns succeed?',[
'He nearly failed to get his own return offer, later managed two interns with very different starting points, and served as an intern director overseeing roughly ten intern managers. That director role involved checking project plans and reviewing ramp-up at three weeks, midpoint progress, and the final evaluation.',
'He sees project completion and velocity as central, with safeguards for badly scoped assignments. A common problem is failing to ask enough early questions. During the first weeks, expectations are low and asking about basics is appropriate; delaying until week six makes the same gap much more consequential. He told interns and new graduates to ask him when a small question consumed more than roughly 30–60 minutes rather than lose repeated hours to an issue an experienced colleague could resolve quickly.',
'Peers matter as well as managers. A shared chat can distribute support when one person cannot answer everything. Peers also provide important evaluation evidence; knowing the intern’s project and behavior helps them give substantive feedback rather than forcing reviewers to reconstruct what happened.'
],3529,3803,followups=[fu('Can an intern compensate by working extreme hours?', ['Reviewers try to distinguish sustainable performance from barely meeting expectations through round-the-clock effort. Repeated code submissions at both early morning and late night can be a warning, especially for someone near the pass threshold.', 'Simon also frames self-care as part of performance. He values exercise, journaling, and morning focus time. He has used a temporary 12–14-hour sprint for about a week and a half to solve a difficult bug, but noticed declining clarity while skipping workouts and drinking more coffee. Occasional intentional sprints and a permanent unsustainable schedule are different choices.'],3803,3957)],speaker='Simon'))
b.append(qa('What workload has felt sustainable, and how does motivation affect it?',[
'He estimates an average around 50 hours a week, with variation for California meetings and his morning routine. He enjoys the work and people, but noticed that the same hours began to feel like a grind when his interest in the product area faded.',
'After reflection, he moved to an infrastructure team and regained enthusiasm and better-quality output. He and the host connect the felt burden of work to interest and motivation as well as hours. This is their experience, not a claim that enjoying work eliminates the need for limits.'
],3957,4091,speaker='Simon'))
b.append(qa('Looking back, what most explains your career growth?',[
'Simon’s central theme is expanding ownership. Early on it means ensuring that a specific task succeeds; later it means owning a team’s success. Curiosity is integral: when another system blocks you, inspect its code and history, understand why a decision was made, and bring a researched question or proposal rather than simply wait.',
'He interprets Meta’s saying that nothing is someone else’s problem as permission to investigate, not as an excuse to ignore people. Cross-functional ownership requires empathy: learn a partner’s goals and incentives, including whether your proposed improvement damages the metric on which they are evaluated. Technical investigation and understanding people both help unblock the work.'
],4091,4273,speaker='Simon'))
b.append(qa('How much of engineering career growth is technical skill versus other behavior?',[
'He does not give a numerical split. He believes a solid technical baseline can support considerable success, including IC5, if an engineer can execute work to good quality, work with designers, use data, and collaborate effectively. Extraordinary ability to solve any technical problem is not his minimum requirement for that level.',
'He regards interpersonal skills as particularly important for gaining trust and opportunities to grow. He also qualifies this: exceptional technical talent can outweigh other weaknesses in some cases. His view is a description of a path he has seen at Meta rather than a universal rule for all roles.'
],4273,4354,speaker='Simon'))
b.append(qa('Why have you stayed at Meta for your whole career so far?',[
'People and flexibility have kept meeting his needs. His initial team grew from two engineers to around 16 before splitting, and because he helped recruit many of them, the young and supportive group felt close. He continues to value colleagues’ empathy and technical skill.',
'Internal mobility let him live and work in several locations, including California, London, and New York, and recently move into work that revived his interest. He did consider leaving when his motivation declined, then chose to give an internal move a chance. He acknowledges that some experiences cannot be found at Meta and that his preferences may change; he has simply not yet reached that point.'
],4354,4516,speaker='Simon'))
b.append(qa('What would you tell yourself when joining as a new graduate?',[
'Ask enough early questions to become productive, then keep investigating why systems work as they do. Be curious, take ownership, and avoid treating every existing constraint as permanent. In a large codebase, past decisions and abandoned experiments may no longer make sense; understanding their history can reveal useful cleanup or a way past a blocker.',
'He pairs that advice with time awareness. A new engineer still needs velocity and should not disappear indefinitely into investigation. Curiosity becomes more valuable once basic productivity is established.'
],4517,4617,speaker='Simon'))
save(sid,'Expand ownership without losing the engineer','Simon’s three-year rise to staff engineering shows how project ownership, mentorship, delegation, communication, and role fit interact.',b,'career',['Opening trailer (0:00–0:55) repeats later exchanges and is represented once in the full interview.','Closing thanks, on-call shout-out, and subscription requests (about 1:16:58 onward) are omitted.'],notes='Read all 7 chunks. Preserved 21 initiating rounds with 13 substantive follow-ups. Speaker identified by the host as Simon; uncertain manager name and garbled internal acronym avoided. Descriptions of ratings, equity, and level expectations are attributed to Simon’s experience, not current universal policy.')
